### ISSUE TITLE
Can't access the container in Controllers

### ISSUE THREAD

**Issue by lordoffreaks** [thephpleague/route#102]
I was playing with this package and I found imposible to do it ... Is that intentional? if so ... why? I can't understand the disadvantage of having access to the service container inside a Controller.

I end up doing it overriding `AbstractStrategy::invokeController` as in [here](https://github.com/lordoffreaks/puzzle/blob/master/src/Route/Strategy/ContainerAwareRestfulStrategy.php#L16) but IMHO it should be accesible.

Thanks in advance and great package!!!

**Comment by philipobenito** [comment]
Accessing the container from the controller would service location which is considered an anti-pattern so it is intentional that it is not instantly accessible but it is not impossible, you'd just have to set up the dependency injection on your controllers to have the container passed in.

**Comment by lordoffreaks** [comment]
Thanks!!!!

**Comment by philipobenito** [comment]
If you need an example of how to pass the container in I can provide one, I would strongly recommend against it though :+1:

**Comment by lordoffreaks** [comment]
I was having a look and [here](https://github.com/thephpleague/route/blob/1.x/src/Strategy/RestfulStrategy.php#L18) looks like the best place to do it to properly inject the container as a dependency.

Anyway examples are welcome! :-D
