### ISSUE TITLE
Middleware like filters

### ISSUE THREAD

**Issue by mbunge** [thephpleague/route#112]
In addition to strategies I would like to add middleware-like filters. A filter could be added to a filter collection of an route. A filter could be an invokable or callable. Filters are executed on dispatching a route. Filters are aware of request, response, route and passed dispatch vars.

**Comment by philipobenito** [comment]
Per route and per group PSR-7 middlewares are currently in the works where you will have access to the request and response objects, as for route cars, they would still only be passed to a strategy, this is to ensure maximum compatibility with middleware dispatchers.
