### ISSUE TITLE
Suggestion: Depend on container-interop instead of League/Container directly?

### ISSUE THREAD

**Issue by darkphoenixff4** [thephpleague/route#114]
Was just wondering, it doesn't look like League/Route needs to use a container except to fetch certain components it needs for routing and dispatching.  If that's so, why not depend on and use https://github.com/container-interop/container-interop instead of depending on League/Container directly?  That would allow a user to provide their own DI container while still using the routes.

**Comment by philipobenito** [comment]
This is already the case, league/container is provided by default for ease of getting started, but it can be swapped out for any container-interop implementation

**Comment by Isinlor** [comment]
It is not the case. The package is expecting immutable implementation of container trough `League\Container\ImmutableContainerAwareTrait` that must return instance of `\League\Container\ImmutableContainerInterface`. Therefore it seems like you currently depend on this immutability or could depend in the future.  AFAIK composer can suggest packages implementing container-interop during installation. Why just not get rid of this dependency and allow composer to handle the requirement of implementing container-interop?
