### ISSUE TITLE
Add example of setting a response header

### ISSUE THREAD

**Issue by aaronpk** [thephpleague/route#117]
As far as I can tell, there are no examples of how to set a response header for the new 2.0 version. It would be helpful if the "Hello World" example showed how to set a header, or in the [Request Response Strategy](http://route.thephpleague.com/request-response-strategy/) page too.

**Comment by philipobenito** [comment]
This is a difficult one as league/route isn't responsible for that, whichever PSR-7 implementation is. So if I were to start showing examples of dealing with the HTTP layer I would have to give an example of everything.

The answer for this particular question can be found here https://github.com/zendframework/zend-diactoros/blob/master/doc/book/usage.md#manipulating-the-response
