### ISSUE TITLE
FastRoute outdated (0.7 vs 1.0.0)

### ISSUE THREAD

**Issue by wouterds** [thephpleague/route#121]
Hi

The first stable version of FastRoute was released last month but this package seems to be stuck on 0.7.
Is there a specific reason why it's not on 1.0.0 yet?

Kind regards,
Wouter

**Comment by hannesvdvreken** [comment]
Because technically then league/route should get a new major release then. Unless fast route 1.0.0 is backwards compatible with 0.7

**Comment by hannesvdvreken** [comment]
2 x then. Sorry 'bout that.

**Comment by philipobenito** [comment]
There's a new major version coming soon so it will be bumped then
