### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by FatBoyXPC** [thephpleague/route#125]
While typically this would probably be split among multiple issues, I actually want to take a stab at doing this on my own and submitting a PR, so I figured I wouldn't clutter up the issues (though there aren't any!).

Intended features:
- Base namespace for controllers
  - something like `$route->setNamespace()`
- Set namespaces on groups
  - `$route->group()->setNamespace()`
- Nested groups
- Allow `setStrategy()` on groups
  - `$route->group()->setStrategy()`

**Comment by FatBoyXPC** [comment]
PR's incoming soon. Regarding nested groups:

Which implementation would you prefer? RouteCollection `$groups` property can be `ArrayIterator` instead, such as:
```
    public function __construct(
        ContainerInterface $container = null,
        RouteParser        $parser    = null,
        DataGenerator      $generator = null
    ) {
        $this->container = ($container instanceof ContainerInterface) ? $container : new Container;

        // build parent route collector
        $parser    = ($parser instanceof RouteParser) ? $parser : new StdRouteParser;
        $generator = ($generator instanceof DataGenerator) ? $generator : new GroupCountBasedDataGenerator;
        parent::__construct($parser, $generator);

        $this->groups = new ArrayIterator([]);
    }
```

or we can pass by reference in the `processGroups()` foreach:
```
    public function processGroups()
    {
        foreach ($this->groups as $key => &$group) {
            unset($this->groups[$key]);
            $group();
        }
    }
```

Both of these retain backwards compatibility thankfully. My initial idea was to invoke `$group()` early rather than store it in the `$groups` array, but that means `group()` will not return a `RouteGroup` object.

Your thoughts? I think I'm more of a fan of the `ArrayIterator` approach rather than `foreach` with a reference.

**Comment by philipobenito** [comment]
Strategies are covered by #139 dues to be merged, default/base namespaces are not something I'm looking at right now though.

**Comment by FatBoyXPC** [comment]
Crap, I got sidetracked by work and forgot about this. i actually have a lot of this work done on my own repo - would you accept a PR after I finish making sure I have adequate test coverage?

**Comment by philipobenito** [comment]
I'm not convinced on the namespace functionality as things stand but may be open to it in the future.

**Comment by FatBoyXPC** [comment]
Well the idea is to not have to type out a namespace to a controller, especially if there are multiple controllers in the same namespace.
