### ISSUE TITLE
NotFoundException Dispatcher

### ISSUE THREAD

**Issue by bastienff** [thephpleague/route#126]
Hello, i am upgrading from v1 and i found my self into this dilema.

Even from scratch following the Hello World example i get this error:

```
Fatal error: Uncaught exception 'League\Route\Http\Exception\NotFoundException' with message 'Not Found' in F:\xampp\htdocs\sistema\vendor\league\route\src\Dispatcher.php on line 76
#0: League\Route\Dispatcher:handleNotFound F:\xampp\htdocs\sistema\vendor\league\route\src\Dispatcher.php:35
#1: League\Route\Dispatcher:handle F:\xampp\htdocs\sistema\vendor\league\route\src\RouteCollection.php:117
#2: League\Route\RouteCollection:dispatch F:\xampp\htdocs\sistema\index.php:48
```

I am wrecking my head around, i would love your insides on this.

PD: Win 10 64 bits / XAMPP PHP 5.6.21

**Comment by philipobenito** [comment]
What is your base URL for your application?

**Comment by bastienff** [comment]
My URL base is localhost/sistema/

**Comment by philipobenito** [comment]
The problem here is that Apache is setting your `REQUEST_URI` as `/sistema/{whatever}` rather than `/{whatever}`.

You could rewrite this using htaccess or a simple fix is to remove that part of the route before the Request object is built.

Very early in your script you can do this:

```php
$uri = '/sistema';
$_SERVER['REQUEST_URI'] = substr($_SERVER['REQUEST_URI'], (strlen($uri)));
```

This should work with a standard htaccess like below.

```
<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteBase /

    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule ^ index.php [QSA,L]
</IfModule>
```

**Comment by bastienff** [comment]
Thanks a lot. htaccess code didn't work for me, i guess is something with XAMPP but modifiying $_SERVER['REQUEST_URI'] works great.

Again thanks a lot.

**Comment by philipobenito** [comment]
👍  no problem

**Comment by JayyWalker** [comment]
Hey, sorry to open this again, but I'm having the same issue. My `REQUEST_URI` is fine. My base uri is `lux.192.168.0.28.nip.io`.

**Comment by ycrao** [comment]
@bastienff some question , but I have got a solution, see #161

**Comment by pbrilius** [comment]
Doesn't work with an official [docs](https://route.thephpleague.com/5.x/usage/). It always triggers 404 **Not Found** error.

**Comment by philipobenito** [comment]
Will need a lot more information than this to help you, most likely candidates are your web server, check request paths are correct etc

**Comment by pbrilius** [comment]
@philipobenito It's working on pure PHP server like ` php -S 0.0.0.0:4121 -f index.php` - on LAMP setup it's missing `.htaccess` support.

**Comment by philipobenito** [comment]
The router doesn’t do anything with .htaccess, it just uses values the server makes available to the script.

**Comment by wesamly** [comment]
For the example listed in https://route.thephpleague.com/5.x/usage/

```php
$request = Laminas\Diactoros\ServerRequestFactory::fromGlobals(
    $_SERVER, $_GET, $_POST, $_COOKIE, $_FILES
);
// Removes the prefix from Uri path: /sistema/{whatever} becomes /{whatever}
$request->withUri($request->getUri()->withPath(rtrim(pathinfo($_SERVER['PHP_SELF'], PATHINFO_DIRNAME), '/')));
// Rest of code...
```
