### ISSUE TITLE
Registered Inflector Method Is Not Called In Controller

### ISSUE THREAD

**Issue by rendyep** [thephpleague/route#128]
![screenshot from 2016-08-16 15 00 31](https://cloud.githubusercontent.com/assets/5343517/17692130/606b685e-63c2-11e6-83f0-b0b4c1fced55.png)

Controller:
```PHP
use Psr\Http\Message\ServerRequestInterface;
use Zend\Diactoros\Response;
use Qasico\Component\Http\Controller\StandardController;
     
class HomeController extends StandardController
{
    public function indexAction(ServerRequestInterface $request)
    {
        return new Response($this->getView()->render('Front::home/index'));
    }
}
```

StandardController:
```PHP
use Qasico\Component\Http\View\ViewAwareInterface;
use Qasico\Component\Http\View\ViewAwareTrait;

class StandardController extends AbstractController implements ViewAwareInterface
{
    use ViewAwareTrait;
}
```

Inflector:
```PHP
$this
    ->container
    ->inflector('Qasico\Component\Http\View\ViewAwareInterface')
    ->invokeMethod('setView', ['service.http.view'])
;
```

Route:
```PHP
$router->map('GET', '/', 'PasarLaut\Bundle\Front\Controllers\HomeController::indexAction');
```

I think the problem is the inflector does not invoke `setView` in my controller.
Is there any help with this issue?

**Comment by philipobenito** [comment]
Have you added a definition for your controller to the container?

`$container->add('Qasico\Component\Http\Controller\HomeController');`

If the controller has not been registered with the container then it will just be instantiated and not resolved from the container, hence the inflector not being invoked.

**Comment by rendyep** [comment]
Thanks @philipobenito, the problem is now solved.

I just can't move on from route 1.x, where it works without adding the controller class to the container.

**Comment by philipobenito** [comment]
Yeah, I made everything a little more explicit as I had times where I was working with people who didn't understand where their objects were coming from before.
