### ISSUE TITLE
Where should I commit Japanese document?

### ISSUE THREAD

**Issue by mitsuru793** [thephpleague/route#130]
I'm a Japanese, so I try to write a Japanese document about this library.
This may improve a share of Japanese and I'll have more information from others.

Which should I commit it to a branch 'gh-pages-v2' or to my blog?

**Comment by philipobenito** [comment]
Yes, please, when I have a little more time I'll integrate it in to the main branch. Thanks.

Sent using Boxer

On 1 Oct 2016 06:58, mitsuru793 <notifications@github.com> wrote:

I'm a Japanese, so I try to write a Japanese document about this library.
This may improve a share of Japanese and I'll have more information from others.

Should I commit it to a branch 'gh-pages-vs' or to my blog?

**Comment by mitsuru793** [comment]
@philipobenito 
Thank you very much! I'll write to the branch 'gh-pages-v2'.

**Comment by philipobenito** [comment]
Closing this as it is not an issue. Pull requests are welcome with documentation.

**Comment by mitsuru793** [comment]
@philipobenito 
I had been busy, so I didn't try it. I'm sorry.
I wrote Japanese document on my project. So I don't have to write Japanese doc.
However, I think to post about it on my blog.

Thank you very much. I
