### ISSUE TITLE
Handling Method Not Allowed and Route Not Found Exception

### ISSUE THREAD

**Issue by teliov** [thephpleague/route#131]
Having an issue with handling the mentioned exceptions. Was about to make a pull request when I saw that @philipobenito already did something like that with strategy decorations here [#119](https://github.com/thephpleague/route/pull/119/commits/536f1ed2046423ba343e29e29df1334a3d3179e1). This would be really neat, the only alternative that comes to mind is a dirty looking try/catch block at the point of dispatch.

**Comment by philipobenito** [comment]
#119 has now been merged to master.
