### ISSUE TITLE
Can't use container in Strategy?

### ISSUE THREAD

**Issue by aviggngyv** [thephpleague/route#133]
Hi, 

![20161114123106](https://cloud.githubusercontent.com/assets/7891096/20253427/3e8777ce-aa66-11e6-8ca5-4e5cd288ab97.png)

![20161114122854](https://cloud.githubusercontent.com/assets/7891096/20253389/f469949c-aa65-11e6-932a-d28d9a149233.png)

I'm just wondering why it's empty, I want to try use Dependency injection in my Controller to inject anything. 

thanks.

**Comment by aviggngyv** [comment]
Surprise! 

yes, I've solved this problem! I think maybe, just maybe , other guys also need this feature, so I want to share this dirty but useful solution :

1. edit this file league\route\src\RouteCollection.php, add code

    /**
     * Get the container.
     */
    public function getContainer()
    {
      return $this->container;
    }

2. modify this file league\route\src\Strategy\ParamStrategy.php

`class ParamStrategy extends AbstractStrategy implements StrategyInterface
{
    /**
     * {@inheritdoc}
     */
    public function dispatch(callable $controller, array $vars, Route $route = null)
    {
        if (method_exists($route->getContainer(), 'call')) {
            $response = $route->getContainer()->call($controller, $vars);

            return $this->determineResponse($response);
        }

        throw new RuntimeException(
            sprintf(
                'To use the parameter strategy, the container must implement the (::call) method. (%s) does not.',
                get_class($route->getContainer())
            )
        );
    }
}`

then , you can inject anything in your Controller . enjoy.

**Comment by philipobenito** [comment]
The container is provided by a trait in the abstract strategy, `$this->getContainer()` from any strategy will provide the container.

The param strategy uses reflection to inject dependencies to the controller method, however, this strategy is being removed in version 3 in favour of a more structured approach where you get the request and response objects and handle other dependencies through constructor or setter injection on the controller class.
