### ISSUE TITLE
Route 2.x (PSR-7) and Sessions

### ISSUE THREAD

**Issue by odan** [thephpleague/route#136]
I try to migrate to Route 2.x, but now all routing and dispatching is built around PSR-7.
For me there is an small "issue" with PSR-7 in combination with native PHP sessions (ext/session). 

The question is: How to deal with Route 2.x (PSR-7) and PHP sessions?
How can I start/set/get/clear session values?
Is there a "thephpleague/session" package or any other solution for this problem?

I started a quick research:

1. https://github.com/psr7-sessions/storageless
Session data is directly stored inside a session cookie as a JWT token.
This is not what I'm looking for.

2. https://github.com/oscarotero/psr7-middlewares/blob/master/src/Middleware/PhpSession.php
How to get/set/clear session values? 

3. http://paul-m-jones.com/archives/6310
https://github.com/relayphp/Relay.Middleware/blob/1.x/src/SessionHeadersHandler.php
[…] However, as you start to need finer control over the HTTP response in your … […]
Looks like a "dirty" trick with ini parameters. 
Not for complex session operations.

Rasmus Schultz says: 

> I’m afraid there is no way to make the session library co-exist peacefully with a modern, PSR-7 (and middleware) based application stack.

Does the PSR-7 concept really fits into the PHP environment?
Is PSR-7 too "dogmatic" and little "pragmatic"?

Back again to my question... ist there a "League" solution for this problem?

**Comment by hannesvdvreken** [comment]
Am I correct if I'd say this is not a problem of league/route?

Try using a middleware (in a middleware stack by relayphp or middleman) to edit the Psr\Http\Message\ServerRequestInterface. But it's possible I didn't fully get your question.

**Comment by odan** [comment]
I know this is a little bit offtopic, but I'm looking for a solution in combination with League Route 2.x.

There is an implication if you try to migrate to League Route 2.x. You need a implementation of PSR-7 (zendframework/zend-diactoros) and a middleware dispatcher (relayphp) and (optional) a container. But this is not a problem for me. 

The whole HTTP request/response is handled by the PSR-7 implementation, with the exception of cookies and sessions. A HTTP cookie/session can be a part of the HTTP request/response (header). 

I'm looking for a way to set, get and clear session data in a way like Symfony does:
https://symfony.com/doc/current/components/http_foundation/sessions.html

The question is, how to deal with native PHP sessions after migration to Route 2.x (PSR-7)?

**Comment by jamesdb** [comment]
> I'm looking for a way to set, get and clear session data in a way like Symfony does:
https://symfony.com/doc/current/components/http_foundation/sessions.html

[Aura\Session](https://github.com/auraphp/Aura.Session) is nice.

**Comment by odan** [comment]
@jamesdb Auro session is very nice. Thank you.

I've learned that PSR-7 is not designed with HTTP session management in mind.
