### ISSUE TITLE
3.0 Stable Release Question

### ISSUE THREAD

**Issue by baileylo** [thephpleague/route#140]
I'm curious when a stable release will happen for the 3.0 branch, specifically with support of middleware?

Is there anyway I can contribute to help make this happen?

**Comment by philipobenito** [comment]
All being well it should be this weekend.


Sent from my Cyanogen phone

On 15 Mar 2017 16:16, Logan Bailey <notifications@github.com> wrote:

I'm curious when a stable release will happen for the 3.0 branch, specifically with support of middleware?

Is there anyway I can contribute to help make this happen?
