### ISSUE TITLE
Questions about middleware integration

### ISSUE THREAD

**Issue by CMCDragonkai** [thephpleague/route#144]
On the docs for middleware, it shows an example for per-route middleware and group middleware.

1. How does the order of composition work for the per-route middleware? It just shows `$router->get(..)->middleware(...)`, what about `$router->middleware(...)->get(...)`? I assume the HTTP requests should enter each middleware left-to-right, and return through each middleware right-to-left.
2. Can a group have an empty prefix? `$router->group('', function ($router) { ... }`, in some cases, I want to group some routes to have a middleware applied, but not other routes, but they aren't in any different hierarchy.

**Comment by philipobenito** [comment]
Hi, in theory yes that's what happens. Practically, middleware is executed in reverse, the last one added is the first to be executed. You control the path back through by the position in which your middleware​ invokes `$next`.

As for a group without a prefix, that wasn't intended but in theory should work with an empty string.

I do plan on improving the documentation around middleware as soon as I have a bit of spare time.
