### ISSUE TITLE
Uncaught Exceptions when route group has a JsonStrategy set

### ISSUE THREAD

**Issue by brandon14** [thephpleague/route#148]
I have a route group prefixed with /api/v1 and some routes defined inside. I also have the strategy set for the route group to the bundled JsonStrategy.

Lets say the routes defined inside the /api/v1 route group are a GET route on / and a GET route on /welcome. The routes work fine, but if I try to call a route such as /api/v1/test, it will throw a NotFoundException, which is expected as the route is undefined, however the exception is not caught when the route is dispatched. I was under the impression that by setting a JsonStrategy on a route (or route group), exceptions would be caught and a json response would be returned.

I thought it might have been where those routes were undefined, so I tried it by setting the strategy on an individual route, and then throwing a NotFoundException from within the controller function, and it will fail with an uncaught exception. Here is some example code to illustrate my problem:
-- file: index.php
```php
<?php

use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;

require '../vendor/autoload.php';

$container = new League\Container\Container;

$container->share('response', Zend\Diactoros\Response::class);
$container->share('request', function () {
    return Zend\Diactoros\ServerRequestFactory::fromGlobals(
        $_SERVER, $_GET, $_POST, $_COOKIE, $_FILES
    );
});

$container->share('emitter', Zend\Diactoros\Response\SapiEmitter::class);

$route = new League\Route\RouteCollection($container);

$route->map('GET', '/', function (ServerRequestInterface $request, ResponseInterface $response) {
    $response->getBody()->write(json_encode(['message' => 'hey']));

    throw new \League\Route\Http\Exception\NotFoundException();

    return $response;
})->setStrategy(new \League\Route\Strategy\JsonStrategy());

$response = $route->dispatch($container->get('request'), $container->get('response'));
$container->get('emitter')->emit($response);
```

I have also tried setting a route group and setting the strategy for the group:
-- file: index.php
```php
<?php

use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;

require '../vendor/autoload.php';

$container = new League\Container\Container;

$container->share('response', Zend\Diactoros\Response::class);
$container->share('request', function () {
    return Zend\Diactoros\ServerRequestFactory::fromGlobals(
        $_SERVER, $_GET, $_POST, $_COOKIE, $_FILES
    );
});

$container->share('emitter', Zend\Diactoros\Response\SapiEmitter::class);

$route = new League\Route\RouteCollection($container);

$route->group('/api/v1', function($route) {
    $route->map('GET', '/', function (ServerRequestInterface $request, ResponseInterface $response) {
        $response->getBody()->write(json_encode(['message' => 'hey']));

        return $response;
    });
})->setStrategy(new \League\Route\Strategy\JsonStrategy());

$response = $route->dispatch($container->get('request'), $container->get('response'));
$container->get('emitter')->emit($response);
```
It seems after looking in the dispatch function for the RouteCollection, it catches the exception, but I added some debugging to the exception handling and $this->getStrategy() is returning an instance of ApplicationStrategy would would just rethrow the exception. Perhaps I am missing something with setting up the strategies for the routes.

Any insight would be greatly appreciated.

**Comment by brandon14** [comment]
Even throwing a BadRequest exception inside of an individual route with a strategy set will still use the ApplicationStrategy.

Also perhaps this is not possible, but for a route group, if something matches the route group prefix, but matches no defined routes inside the group, would a strategy set for the group still apply to that route dispatch?

**Comment by philipobenito** [comment]
This is very odd, will have a look at trying​ to recreate it tomorrow. What is your set up? Server, PHP version etc?

**Comment by brandon14** [comment]
It was ran on PHP 7.1 with built in PHP server. I can do some more testing using an Apache server if needed.

And I noticed it on a little project I have been working on for my personal website where I was converting my site over to an MVC architecture and using dependency injection. So I was using PHP-DI as the IoC container (it was being passed into the league router and appears to be working fine for resolving dependencies in my controller). I thought it could be due to some of my classes I had wrote like a http Kernel to wrap around the route collection and a basic application object that holds the container and some other stuff. So I created a new test project just using the zend diactoros dictionary and league router with a simple test page and was finding the same results so I am not quite sure what is going on.

I dumped the route collection object just before the route was dispatched and it appears that the strategy is getting set, its just when inside the dispatch functionality it gets the strategy, it just gets the default or application wide strategy instead of one set on the route or route group.

I know the JsonStrategy is working when a route is matched because of the response that is returned from a JsonStrategy route vs one with the default ApplicationStrategy. It just seems that when an exception is raised it is causing some issues.

**Comment by brandon14** [comment]
If I can get some time maybe I could write some tests on the JsonStrategy when exceptions are raised and see if I can't flush out what is happening.

**Comment by brandon14** [comment]
Also in the strategy decorators, you can return a string that is a fully qualified class namespace and function much like in the router mapping to define a controller method, however in my testing I have found that whenever the controller function is called from the strategy decorator (when it is handling an exception), i believe it statically calls the controller function because I was unable to use $this inside of that controller function. This maybe the intended functionality for strategy decorators but I thought I would try to get some clarification on that.

**Comment by philipobenito** [comment]
Is your route definitely matching? My thoughts are that it might not be and that it's not picking up the strategy so a standard `NotFoundException` is being thrown?

**Comment by brandon14** [comment]
I have thrown an exception from within the route controller and it still behaves the same way. If I remove the exception the route returns my JASON as expected.

**Comment by brandon14** [comment]
I was looking at the tests for the JsonStrategy and maybe I am misunderstanding it, but the description says it asserts the strategy builds a json response for a controller that does not return a response, but the test itself asserts that a runtime exception is thrown. Shouldn't the test assert that the strategy builds a json response in the event that a response is not returned?

**Comment by brandon14** [comment]
If the strategy is set to `JsonStrategy` at the app level, then an exception thrown in the controller will return the JSON as expected. However if the app level strategy is still the default (or one that doesn't decorate the exceptions) but the route or route group has the JsonStrategy set, when the exception is handled in the dispatcher, instead of getting the individual route strategy or the route group strategy, it gets the app level strategy, and thus the exception bubbles out.

I believe it to be an issue in getting the strategy in the exception handling for the dispatch method.

**Comment by gerardsmit** [comment]
Got the same issue. 

Setting the strategy on the RouteCollection works, but on the RouteGroup it doesn't work.

| Name           | Value                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|----------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| OS             | `Ubuntu 16.04.2 LTS`                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| PHP version    | `PHP 7.1.4`                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| PHP extensions | `Core, date, libxml, openssl, pcre, zlib, filter, hash, pcntl, Reflection, SPL, session, standard, mysqlnd, PDO, xml, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, igbinary, imagick, imap, intl, json, exif, mcrypt, mysqli, pdo_mysql, pdo_sqlite, Phar, posix, readline, redis, shmop, SimpleXML, soap, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache, xdebug` |

**Comment by philipobenito** [comment]
Will be looking at this properly this week. There are a lot more complications than at first glance, will explain when I have a little more time.

**Comment by jesscarlos** [comment]
I am having the same issue. Setting a strategy globally works but not when I set it on the individual route or group. As a workaround I created middleware that gives me the same result as the Strategy but using a strategy is more ideal.

**Comment by ycrao** [comment]
@jesscarlos the same to you.
