### ISSUE TITLE
[Feature Request] PSR-15 HTTP Middleware support

### ISSUE THREAD

**Issue by itsjavi** [thephpleague/route#150]
I understand that [PSR-15](https://github.com/php-fig/fig-standards/blob/master/proposed/http-middleware/middleware.md) is just a proposal right now (draft status) but It would be nice to start supporting it in a feature branch for example. 

The new PSR was proposed in The PHP League Google group: https://groups.google.com/forum/#!msg/thephpleague/jyztj-Nz_rw/I4lHVFigAAAJ

Due to the fact that `league/route` uses a double pass signature (request + response as middleware arguments) and PSR-15 uses single pass (request), it is incompatible with other router systems like `Aura.Router` and `FastRoute` and in general with any PSR-15 middleware stack.

Please read these articles to understand double pass flaws: https://github.com/middlewares/awesome-psr15-middlewares#articles

There has been also an attempt to make a PSR-15 compatible LeagueRoute middleware, but everything we can do right now seems very hacky: https://github.com/middlewares/ideas/issues/15

**Comment by hannesvdvreken** [comment]
Best to wait till psr-15 is final. In any case, it will be easy to make a middleware for league/route in more than one way.

For example: https://github.com/madewithlove/psr15-bridge/blob/master/src/Middleware.php

**Comment by philipobenito** [comment]
It'll be coming in a v4 release once it's accepted.

On 22 Apr 2017 3:52 pm, Hannes Van De Vreken <notifications@github.com> wrote:

Best to wait till psr-15 is final. In any case, it will be easy to make a middleware for league/route in more than one way.

For example: https://github.com/madewithlove/psr15-bridge/blob/master/src/Middleware.php

**Comment by itsjavi** [comment]
That's good to know @philipobenito 
but you are right @hannesvdvreken it's better to wait until the approval.
Things may change a lot until then.

**Comment by philipobenito** [comment]
Closing as it is road mapped already and not technically an issue.
