### ISSUE TITLE
Is there a way to get a url of a route, from the name including passed parameters?

### ISSUE THREAD

**Issue by RyanHipkiss** [thephpleague/route#151]
I know I can get the path of a route through `$router->getNamedRoute('route.example')->getPath();`, however when I have a route like so:

`$router->get('/{id:number}', 'Controller::action()`)->setName('route.example');`

and I run this method, it returns: `/{id:number}`. Is there a way that I can pass the ID variable when I call `getNamedRoute('route.example')->getPath()` and have it return the built URI?

**Comment by philipobenito** [comment]
You have a couple options here.

1. You can build a URI from the request object.
2. You can build a custom strategy that would provide a controller with the active URI.

You also have access to the route arguments as the third argument in controller callables.

https://github.com/thephpleague/uri could also help you.

**Comment by RyanHipkiss** [comment]
It's completely separate from my Controllers etc (used in a custom twig function for my view). Looks like I'll have to build a custom method that will replace them with the corresponding matches.

Thanks anyway.
