### ISSUE TITLE
Use the middleware without initialising the class?

### ISSUE THREAD

**Issue by RyanHipkiss** [thephpleague/route#152]
Is there a way to do this? I'm using PHP DI and need to inject one of my classes into the middleware's construct. 

I know it's not specifically related to this project, but thought you may know something?

**Comment by jamesdb** [comment]
Setup the middleware class:

```
$container
    ->add(Middleware::class)
    ->withArgument(SomeService::class)
;
```

Pass middleware to router:

```
$router->get(..)->middleware($container->get(Middleware::class))
```

Don't know how this would transfer over to PHP DI, but it shouldn't be too difficult to figure out.

**Comment by philipobenito** [comment]
Yes, as @jamesdb says it's just a case of pulling the class from the container you are using.
