### ISSUE TITLE
Middleware

### ISSUE THREAD

**Issue by bjpayne** [thephpleague/route#153]
**Issue:**
Application middleware is not handled before the route is dispatched so middleware that mutates the request prior the route being dispatched yields undesired results. 

**Example:**
A good example is spoofing HTTP methods on HMTL form requests. The form request sends POST as the HTTP method but an [HTTP Method Override](https://github.com/oscarotero/psr7-middlewares#methodoverride) middleware detects a hidden field and mutates the request to be a PUT/PATCH/DELETE request. In its current state, Route throws an `MethodNotAllowed` exception as the RouteCallable is dispatched prior to the application middleware. The matching route method is PUT but the request is a POST request. My workaround has been to have a pre execution stack that I handle outside of Route and terminate the stack with the route dispatcher but this is redundant. Route should be able to handle this.

**Possible Fix:**
In the `RouteCollection::dispatch` method there needs to be one extra layer where the route is located and added to the end of stack as the last element. If the route does not match throw the `NotFoundException` here. Then just treat the matched route like any other middleware. The required return type of callables is the `ResponseInterface` so it will just end the execution chain there.

Thanks,

Ben

**Comment by philipobenito** [comment]
I'll have to have a look at order, however, as things stand, your example will never work, the route is matched before any middleware is invoked

**Comment by bjpayne** [comment]
I'm thinking you would have to just match the route, then add it to the end of the middleware stack. All of the Route callable signatures should match the PSR-7 middleware callable signature. The matched route would then just get dispatched after the request had passed through all of the middleware.
