### ISSUE TITLE
Access to PUT body parameters

### ISSUE THREAD

**Issue by Preovaleo** [thephpleague/route#155]
Hello,

I don't see anything on how to deal with the PUT body parameters.
I ask you this question as I want to do an API with your tool.
I know that PHP doesn't fill the `$_BODY ` var when you make a PUT request.
But perhaps it's a Diactoros [issue](https://github.com/zendframework/zend-diactoros/issues/144)

Is this possible ?
Regards,

**Comment by hannesvdvreken** [comment]
Hi. Most frameworks in PHP fix this by doing POST but with a _method=PUT in it's body. It's a PHP specific issue.

**Comment by philipobenito** [comment]
Is there any reason you couldn't access the raw body of the request?

**Comment by ozzpy** [comment]
put `$app->pipe(BodyParamsMiddleware::class);` in your pipeline, (I use it on first middleware)
