### ISSUE TITLE
Wrong order of middlewares when using RouteGroup

### ISSUE THREAD

**Issue by khanhicetea** [thephpleague/route#156]
### Issue

```php
$r->group('/a', function ($group) {
    $group
        ->get('/b', $r->to('home', 'index'))
        ->middleware(function($req, $res, $next) {
            $res = $res->withHeader('X-Middleware', 'Route');
            return $next($req, $res);
        });
})->middleware(function($req, $res, $next) {
    $res = $res->withHeader('X-Middleware', 'Group');
    return $next($req, $res);
});
```

### Expected

Group middleware must runs before route middleware

```
X-Middleware: Route
```

### Result

Route middleware runned before group middleware

```
X-Middleware: Group
```

### Possible fix

Adding group middleware after processing all children routes.

**Comment by hannesvdvreken** [comment]
You can fix that by doing 


```php
$r->group('/a', function ($group) {
    $group
        ->get('/b', $r->to('home', 'index'))
        ->middleware(function($req, $res, $next) {
            $res = $res->withHeader('X-Middleware', 'Route');
            return $next($req, $res);
        });
})->middleware(function($req, $res, $next) {
    $res = $next($req, $res);
    return $res->withHeader('X-Middleware', 'Group');
});
```

That's the cool thing about middleware. You can decide wether you run it _before_, or _after_ the inner (`$next`) controllers and middleware.

**Comment by khanhicetea** [comment]
Hmm .. something wrong here, could you recheck ?

The root problem : **Route middleware runs before Group middleware**
So in your case, the result is still the same.

What if I used **group middleware** to check user login and adding a attribute `user` to request then passing new request to **route middleware** ?

Route middleware called before Group middleware so it have no `user` attribute.

**Comment by hannesvdvreken** [comment]
```php
$r->group('/a', function ($group) {
    $group
        ->get('/b', function ($req, $res) {
             // Controller
        })
        ->middleware(function($req, $res, $next) {
            // Before route controller
            $res = $next($req, $res);
            // After route controller
            return $res;
        });
})->middleware(function($req, $res, $next) {
    // Before route specific middleware
    $res = $next($req, $res);
    // After route specific middleware
    return $res;
});
```

Hold on. Did you try this? Am I wrong about my comments in this code sample? Is it not executed as such?

**Comment by khanhicetea** [comment]
This is my testing code (I used XDebug and set breakpoints on [X] statement) and this is the running order I got

```php
<?php

require 'vendor/autoload.php';

use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;

$container = new League\Container\Container;

$container->share('response', Zend\Diactoros\Response::class);
$container->share('request', function () {
    return Zend\Diactoros\ServerRequestFactory::fromGlobals(
        $_SERVER, $_GET, $_POST, $_COOKIE, $_FILES
    );
});

$container->share('emitter', Zend\Diactoros\Response\SapiEmitter::class);

$r = new League\Route\RouteCollection($container);

$r->group('/a', function ($group) {
    $group
        ->get('/b', function (ServerRequestInterface $req, ResponseInterface $res) {
            $res->getBody()->write('<h1>Hello, World!</h1>'); // [5]
            return $res;
        })
        ->middleware(function($req, $res, $next) {
            $a = 1; // [1]
            $res = $next($req, $res); // [2]
            $a = 1; // [7]
            return $res;
        });
})->middleware(function($req, $res, $next) {
    $a = 1; // [3]
    $res = $next($req, $res); // [4]
    $a = 1; // [6]  
    return $res;
});

$response = $r->dispatch($container->get('request'), $container->get('response'));

$container->get('emitter')->emit($response);
```

As I said, the root problem is "Route middleware runs before Group middleware" and this is wrong logic (even we can use any tricks to resolve)

**Comment by hannesvdvreken** [comment]
Ok, seems odd.

Please understand that we can't just change it right now. If we change that, it's a breaking change and we could possibly break a lot of applications that use this router.

Have you tried solving your problem with adding a global middleware on the route collection directly?

Cheers

**Comment by hannesvdvreken** [comment]
@philipobenito can you chime in here and explain why you picked this order over the other?

**Comment by philipobenito** [comment]
The middleware currently works outside in, with the route callable being the last thing that is invoked. Since implementing, I think I have come around to the idea that inside out is nicer, however, as @hannesvdvreken says, it would be a breaking change to reverse now and the next major version will change significantly to become single pass.

That being said, you are completely in control of whether logic is run before or after the next middleware is invoked. If you want your route middleware to be aware of changes made in the group middleware, then invoke `next` as the first action, it's not a "trick" to do that, it's a perfectly valid use case.

As I said, my preference has changed purely because of this, how it is perceived to "work by default", so I now see it as flawed but you can generally achieve what you want to via manipulation of middleware order and structuring them.

Middleware will be getting much more attention in the next major release.

**Comment by philipobenito** [comment]
I'm closing this now, the v4.0.0 will be in the near future once the middleware PSR is available for me to build on. This will mean some major changes to middleware, most likely a complete rewrite of that area.
