### ISSUE TITLE
Could not instance Controller with container.

### ISSUE THREAD

**Issue by vv3d0x** [thephpleague/route#157]
Please provide login for instantiating Controllers with DI Container, because right now I have to write my own strategy and implement a logic for $route->getCallable() which make call inside from
file Route.php line 87

My code flow:

```php
class HomeController extends BaseController
{
  public function home($request, $response) {
    return $response;
  }
}

abstract class BaseController
{
  use \League\Container\ContainerAwareTrait;
}
`

**Comment by philipobenito** [comment]
Apologies but I don't understand what you're asking?

**Comment by vv3d0x** [comment]
Ok, I will try to explain

1. I am using league components: route, container, event
2. I made base application class for specific workflow control
3. all routes are in different files (but this is only a structure)
4. routes will use not a Closure, they will use Controllers logic instead.
5. I want to have feature: register controller for route with dependency container
I mean next:
```php
$router->get('/some/method[/{action}[/{params:.*}]]', 'App\Controllers\SomeController::method');
`

I made investigation with Route and getCallable method, it can use an instance of callable, but it is not very useful to make it outside on route configuring. What if we have a lot of different controllers, than we need to instantiate each of them and pass into router or container manually.

Instead I made BaseController which has ContainerAwareTrait (for implementing container support)
and I implement __constructor
```php
abstract class BaseController
{
  use ContainerAwareTrait;
 
 public function __construct(ContainerInterface $container) {
  $this->container = $container;
 }
}
`
 I want to have a base class which will has some logic.
Route could not instantiate a controller class because $route->getCallable() make call like
$class = new $callable[0]; 

I would like to have option to do some injection via setter or basically it could be better to do that with constructor if we are talking about di container.

**Comment by vv3d0x** [comment]
we can implement di support for containers in next way:
write new strategy and do not use there $route->getCallable(), but it would be better to make support for passing arguments for callable

**Comment by vv3d0x** [comment]
as for me the best solution is next:
replace code in Route.php (method getCallable())
```php
$class = ($this->getContainer()->has($callable[0]))
					    ? $this->getContainer()->get($callable[0])
					    : new $callable[0];
```
with next
```php
$class = ($this->getContainer()->has($callable[0]))
					    ? $this->getContainer()->get($callable[0])
					    : new $callable[0]($this->getContainer());
```

it means that container has a dependency for DI Container and it will has access to different services inside.

**Comment by hannesvdvreken** [comment]
@vv3d0x if you read the documentation (http://route.thephpleague.com/controllers/), you will see you can do:

```php
$router->get('/acme/route', 'AcmeController::someMethod');
```

If you're `AcmeController` has a constructor, the container will try to inject whatever is necessary.

```php
class AcmeController
{
    public function __construct(Dependency $dependency)
    {
    }

    public function someMethod()
    {
    }
}
```

If you have any issues with how the container should inject something, please refer to the documentation for league/container: http://container.thephpleague.com/2.x/

For your example: 

```php
abstract class BaseController
{
    use ContainerAwareTrait;
}
```

You could setup an "inflector"

```php
$container->inflector('BaseController')
     ->invokeMethod('setContainer', [$container]);
```

**Comment by vv3d0x** [comment]
I have read the doc http://route.thephpleague.com/controllers/
And try to investigate, because previously I used Slim framework and this logic implemented there by default  in route (Controller has dependency for container) [https://www.slimframework.com/docs/objects/router.html](url) (#Registering a controller with the container) and I can not understand why controller does not have basic dependency for container by default.

I think controller should has access for internal services by default. and all they are defined in container.

Or maybe, can you explain why controller do not has this dependency ? and you decide to use this logic by Container (delegate or inflect)

**Comment by philipobenito** [comment]
I don't have much time right now so haven't read the whole thread yet. Just want to touch on your question above though.

> Or maybe, can you explain why controller do not has this dependency ?

Passing the container in to your controllers and pulling dependencies from the container is actually Service Location, not Dependency Injection and is considered an anti pattern for many reasons.

It is something you *can* do but I don't recommend that you do. A better approach is to have your controllers set up to receive their dependencies directly via the constructor. If you do that, you can then define those dependencies in the container and pass that container to the `RouteGroup`, once you do that, the container will handle wiring everything together.

**Comment by vv3d0x** [comment]
Ok, I will try to play with our explanation.
P.S. singleton is anti-pattern to, but in some cases, its use is justified

**Comment by philipobenito** [comment]
> P.S. singleton is anti-pattern to, but in some cases, its use is justified

Hence why it is possible, however, there are very few situations where this would be the case with a controller so it will never be a default.

**Comment by vv3d0x** [comment]
what about implementation in Route method which will return you a raw value for $callable.
method getCallable() do some logic, but you can not made own strategy which will do some manipulation with Route->callable.

**Comment by hannesvdvreken** [comment]
@vv3d0x You can very much create your own strategy if you like.

http://route.thephpleague.com/strategies/

```php
$router = new League\Route\RouteCollection();
$router->setStrategy($yourStrategy);
```

But as far as I understand, you won't need to that. You want the Container to be passed on to every controller's constructor. @philipobenito and I both wouldn't do that, but it's totally up to you! You can do it, if you like to.

```php
$container = new League\Container\Container();

// This will inject the container whenever you type hint it in a controller's constructor
$container->share(Container::class, $container);

$route = new League\Route\RouteCollection($container);

$route->get('/acme', 'AcmeController::someMethod');

class AcmeController
{
    public function __construct(Container $container) {
        $this->container = $container;
    }
}
```

I'd even use `Psr\Container\ContainerInterface` instead as a type hint in the constructor, and where you bind it to the container itself.

Is that clear?

**Comment by arryanggaputra** [comment]
@hannesvdvreken Hi there, you just mention `You want the Container to be passed on to every controller's constructor. @philipobenito and I both wouldn't do that` , do you mind to explain why?

thank you.

**Comment by hannesvdvreken** [comment]
Yeah sure.

Instead of injecting the container in a controller, you can let the container inject whatever the controller needs. The router will actually use the container to create a controller object.

For example if you have a controller

```php
class Index
{
    public function __construct(Container $container)
    {
        $this->container = $container;
    }

    public function hello()
    {
        $view = $this->container->get(Twig::class);

        $template = $view->render('hello');

        return new HtmlResponse($template);
    }
}
```

So, the controller here depends on the container and also on Twig to render views. But if we let the router use the container to create the controller we can do:

```php
class Index
{
     public function __construct(Twig $view)
     {
         $this->view = $view;
     }

    public function hello()
    {
        $template = $this->view->render('hello');

        return new HtmlResponse($template);
    }
}
```

This way it's also easier to unit-test our controller:

```php
$view = $this->createMock(Twig::class);
$controller = new Index($view);

$view->method('render')->with('hello')->willReturn('bar');

$response = $controller->hello();
$this->assertSame('bar', (string) $response->getBody())
```

Or something. Very easy.

**Comment by arryanggaputra** [comment]
@hannesvdvreken  Cool, i already use something like this :
```php
class Index
{
     public function __construct(Twig $view)
     {
         $this->view = $view;
     }

    public function hello()
    {
        $template = $this->view->render('hello');

        return new HtmlResponse($template);
    }
}
```

But, i just try this :
```php
use League\Container\Container;

class HomeController
{
    public function __construct(Container $container)
    {
        $this->container = $container;
    }
```

I got this `Argument 1 passed to League\Container\Container::__construct() must implement interface League\Container\ServiceProvider\ServiceProviderAggregateInterface, string given`

**Comment by arryanggaputra** [comment]
@hannesvdvreken btw, how to call the container from another class? Example, i have a Models, how can i call the container? For now, what i did is create a function to recreate the container instance : 

```php
class Application
{
    private static $instance = null;

    private function __construct()
    {
        $dependencies = require_once root_path('config/dependency.php');
        $container    = new \League\Container\Container;

        /**
         * Container has the power to automatically resolve your objects
         * and all of their dependencies recursively by inspecting the type hints
         * of your constructor arguments
         *
         * @see  http://container.thephpleague.com/3.x/auto-wiring/
         */
        $container->delegate(
            new \League\Container\ReflectionContainer
        );

        foreach ($dependencies as $interface => $implementation) {
            $container->share($interface, $implementation);
        }

        $this->container = $container;
    }

    public static function make()
    {
        // Check if instance is already exists
        if (self::$instance == null) {
            self::$instance = new Application();
        }
        return self::$instance;
    }

    private function __clone()
    {
        // Stopping Clonning of Object
    }

    private function __wakeup()
    {
        // Stopping unserialize of object
    }
}

```

**Comment by hannesvdvreken** [comment]
> Argument 1 passed to League\Container\Container::__construct() must implement interface League\Container\ServiceProvider\ServiceProviderAggregateInterface, string given

I don't think that's related to the controller you show there. Go find where you do `new Container(...` something is wrong there.

**Comment by hannesvdvreken** [comment]
@arryanggaputra 

```php
foreach ($dependencies as $interface => $implementation) {
    $container->share($interface, $implementation);
}
```

I would advice you to use ServiceProvider classes. See http://container.thephpleague.com/2.x/service-providers/ for documentation.

2nd: I wouldn't use a constructor to make a new container. Instead try something like this:

```php
class Application
{
    private static $instance = null;

    public static function make()
    {
        // Check if instance is already exists
        if (self::$instance == null) {
            self::bootstrap();
        }
        return self::$instance;
    }

    private static function bootstrap()
    {
        $dependencies = require_once root_path('config/dependency.php');
        $container    = new \League\Container\Container;

        /**
         * Container has the power to automatically resolve your objects
         * and all of their dependencies recursively by inspecting the type hints
         * of your constructor arguments
         *
         * @see  http://container.thephpleague.com/3.x/auto-wiring/
         */
        $container->delegate(
            new \League\Container\ReflectionContainer
        );

        foreach ($dependencies as $interface => $implementation) {
            $container->share($interface, $implementation);
        }

        self::$instance = $container;
    }
}
```

I would personally call it `ContainerFactory` instead of `Application`, because `Application::make()` looks too much like `App::make()` in Laravel but it does something different.
