### ISSUE TITLE
I cannot figure out how to declare what should happen when no routes are matched.

### ISSUE THREAD

**Issue by thinsoldier** [thephpleague/route#164]
I am getting "Fatal error: Uncaught exception 'League\Route\Http\Exception\NotFoundException' with message 'Not Found'"

Should I wrap `$route->dispatch()` in a try catch or is there some special 404 route or catch-all I can set up?

Or can I define some kind of super greedy regular expression addPatternMatcher alias and set that as the very last route so if no router before that was matched, it will be run?

I'm trying to make a view that says "Page not Found" that uses the same layout as the rest of the project.

**Comment by philipobenito** [comment]
There are two ways to do this, one is as you mentioned, wrapping dispatch in a try catch, or by creating a custom strategy that handles not found in a different way.

I'll mirror what I said on another issue that this isn't a framework so we make no assumptions around how not found should be handled.

Take a look here http://route.thephpleague.com/custom-strategies/ for custom strategies, as well as the default strategies in the repository for guidance.
