### ISSUE TITLE
PSR-15 support

### ISSUE THREAD

**Issue by willemstuursma** [thephpleague/route#167]
Following #150, PSR-15 has now been accepted.

I understood that v4 will support PSR-15.

Is there a roadmap / timeline or a way to contribute PSR-15 support?

**Comment by hannesvdvreken** [comment]
Here's a quick class I use myself to use this route package as a middleware in a PSR-15 stack:

```php
<?php

namespace App\Infrastructure\Middleware;

use League\Route\RouteCollection;
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Server\MiddlewareInterface;
use Psr\Http\Server\RequestHandlerInterface;
use Zend\Diactoros\Response;

class LeagueRouterMiddleware implements MiddlewareInterface
{
    /**
     * @var RouteCollection
     */
    private $router;

    /**
     * @param RouteCollection $router
     */
    public function __construct(RouteCollection $router)
    {
        $this->router = $router;
    }

    /**
     * @param ServerRequestInterface $request
     *
     * @return ResponseInterface
     */
    public function process(ServerRequestInterface $request, RequestHandlerInterface $handler): ResponseInterface
    {
        return $this->router->dispatch($request, new Response());
    }
}
```

Have fun!

**Comment by willemstuursma** [comment]
It's not about using the router as middleware, its about adding support for PSR-15 to `\League\Route\Middleware\StackAwareTrait::middleware()`. Though, the other way around might also work. 

@shirshir what do you think?

**Comment by hannesvdvreken** [comment]
@willemstuursma Right! Thanks for pointing that out for me 🙈

Yeah allowing PSR-15 middleware shouldn't be too hard. Maybe even without a new major version by allowing old and new style (or with a different method name).

**Comment by philipobenito** [comment]
Most of the next major version is complete, I'm hoping to get PSR-15 added and a release drafted over easter weekend

**Comment by vimist** [comment]
@philipobenito Did you get anywhere with the PSR-15 integration?

**Comment by philipobenito** [comment]
It's coming, I've just been slowed down a little, life happens lol, hopefully next couple of weeks though

**Comment by stebke** [comment]
Any news on this?

**Comment by philipobenito** [comment]
Been on holiday but there will be a major version release this week

**Comment by philipobenito** [comment]
yes https://github.com/thephpleague/route/pull/178 just writing docs, will be released in the next couple of days
