### ISSUE TITLE
No decorator for Errors

### ISSUE THREAD

**Issue by willemstuursma** [thephpleague/route#169]
Currently, the `\League\Route\Strategy\StrategyInterface` interface does not offer a decorator that can handle `\Error` class throwables.

Of course this is because of PHP < 7 support.

But it would be a nice addition to the next major version. 

If we cause an Error somewhere in one of our handlers we'd like to respond with a nice response instead that can be controlled from our implementation of `\League\Route\Strategy\StrategyInterface`. 

Alternatively, `symfony/polyfill-php70` could be used to create a PHP5  and 7 compatible implementation.

**Comment by philipobenito** [comment]
It is planned for the next major release, hoping that will be drafted around Easter
