### ISSUE TITLE
[Feature Request] Allow using another container than league/container

### ISSUE THREAD

**Issue by hansott** [thephpleague/route#172]
Since there's a type-hint for `Psr\Container\ContainerInterface`, why is there a required dependency on `league/container`?

It would be nice if we could use any container implementation. 😏

**Comment by philipobenito** [comment]
Just simply to make it usable out of the box, it’s absolutely fine to use any other container with it.

**Comment by hansott** [comment]
Hi, thanks for your answer. I can submit a PR tonight to remove the dependency and update the docs?

**Comment by philipobenito** [comment]
I think you misunderstand, it’s there to allow users to pick it up and use easily, so it will stay, however, anyone who wants to is free to use a different container.

**Comment by hansott** [comment]
First, I would like to say thank you for this package, it works great. 🙇 

I do understand. The only thing that I suggest to change:

`composer require league/route`

to

`composer require league/route league/container`

Right now there's a hard dependency on `league/container`. If you prefer to use another container  you can (like you're saying) but `league/container` will be installed anyway because it's a dependency in `composer.json`.

We could add this in `composer.json` to make it clear that this library needs a container implementation:

```json
{
    "suggest": {
        "league/container": "Required, unless you're planning to use another container implementation"
    }
}
```

**Comment by philipobenito** [comment]
The point is that if you only install league/route without a container, it is broken. It’s a barrier to entry so it’s not something I’d consider removing, for the type of package route is anyway.

I have to go with the majority use case, which is heavily rooted in using league/container, it is only the minority who want to replace it, so with that already being possible with minimal impact, I’m comfortable with how it currently is.

I don’t think it’s too much of an issue for container to be installed and not used, could even be removed in your build process.

**Comment by hansott** [comment]
Alright, fair enough. Thanks for your time & feedback!

I'll close my issue. 😉

**Comment by turanct** [comment]
i do think it's an issue to install things you don't need. e.g. for security considerations, or even for dependency resolving issues.

To solve the problem, you could make the main package depend purely on the interface, and create an adapter package which depends on both the main package and the league container. People can then just install that adapter package and get a working system, while people who want to use just the "route" part and combine it with their own container can do so as well by installing the main package, without having to install other packages they don't need.

**Comment by Isinlor** [comment]
@turanct I looked trough the issues and it was raised many times with the same answer: https://github.com/thephpleague/route/issues/40 https://github.com/thephpleague/route/issues/52 https://github.com/thephpleague/route/issues/86

I also consider it a pity.

**Comment by Arcesilas** [comment]
Hi,

Since `League/Container` provides `psr/container-implementation`, maybe `Route` could require `psr/container-implementation`: the package is not broken, since it requires a package to provide this implementation. If no such package is installed, `Route` will not be installed.
`League/Container` should still be listed in the `require-dev` section of `composer.json` for the tests to work.

By the way, `Route` requires a PSR-7 implementation to work:
> You will also need to install an implementation of PSR-7.
Without that, it is "*broken*". Therefore, you have to install an additional package like Zend Diactoros to use it.

**Comment by Arcesilas** [comment]
Oh, ok, sorry...
