### ISSUE TITLE
Uri generation

### ISSUE THREAD

**Issue by whera** [thephpleague/route#174]
use generator to create URIs based or your named routes. Example for the code above:
```php

<?php

// route path is '/blog/posts/{id}' for 'blog.post' route
$uri = $route->generate('blog.post', ['id' => 100]);

echo $uri; // outputs "/blog/posts/100"
```

**Comment by whera** [comment]
??

**Comment by philipobenito** [comment]
Sorry, I missed this, the router does have named routes and from that you can get a route object with the route path. However, it does not generate the route with options you pass to it. You could create a wrapper or route generator quite easily to do this though so it's not impossible. It's not currently something that would be considered for the code base though as I have yet to come up with a good solution to it that wouldn't require either an extension of some sort of base controller or passing the router around in your controllers. It's on my list of possibilities if ever I find something I'd be happy with so suggestions are welcome.

**Comment by whera** [comment]
Thanks for the answer.
I'll implement the generator

**Comment by Arcesilas** [comment]
Hi,

I've written a package that provides this feature among other appreciable stuff: https://github.com/Xocotlah/SmartController#url-builder

**Comment by franzose** [comment]
Hi, @whera, @Arcesilas, @philipobenito! I've just published the URL generator library for the League Route. Please, don't hesitate to check out, review, share and report issues if you find a bug or have a question!
