### ISSUE TITLE
Increase the minimum PHP version to PHP 7

### ISSUE THREAD

**Issue by willishq** [thephpleague/route#176]
Since PHP <5.6 is already EOL and PHP 5.6 is EOL in January 2019, should we consider increasing the minimum version of PHP to PHP 7?

Part of the reason for wanting to do this is that the [psr-15](https://www.php-fig.org/psr/psr-15/) package requires PHP 7+ and as such, we can not utilise the interfaces to create compliant middleware, as seen the failing tests in #175

**Comment by philipobenito** [comment]
Will be in the next major release this week
