### ISSUE TITLE
Route level strategy

### ISSUE THREAD

**Issue by sasanrose** [thephpleague/route#177]
What I'm trying to do is to have a strategy for route collection and a separate strategy for a route. However, whenever an exception happens during the dispatch of that route, it always falls back to the route collection strategy rather than the exception decorators that I defined for my route. The only method in my route specific strategy that is being used is getCallable method:

```php
$router = new Route\RouteCollection($container);
$router->setStrategy(new Strategy());
$router->get('/_health', $callable)->setStrategy(new HealthCheckStrategy());
```

**Comment by philipobenito** [comment]
Can you let me know what version you are using so I can have a look please?

**Comment by philipobenito** [comment]
There has been a bit of an overhaul to the strategy system to better handle what happens in these situations #178
