### ISSUE TITLE
unhandled Fatal error in Route->getCallable()

### ISSUE THREAD

**Issue by MIvanIsten** [thephpleague/route#179]
There is a `new $callable[0]` at line 87 of Route.php without checking existence of the class.
Resulting a fatal error if the class does not exists.
Should throw exception if `!class_exists($callable[0])`

**Comment by philipobenito** [comment]
I don't think it is a problem to let this bubble out personally

**Comment by MIvanIsten** [comment]
The problem is, it is not throwing an exception to handle, but stopping script execution with fatal error.

**Comment by philipobenito** [comment]
My point is you can’t recover from it, the only benefit I see to switching to an exception being thrown is a more useful error description, but it introduces a lot more conditional paths just for that. Not completely against the idea, just weighing it up

**Comment by MIvanIsten** [comment]
You are right, can't recover from it.
But if it throws exception, the Strategys exception handler can catch it and generate proper error response.
