### ISSUE TITLE
Multiple dispaches break unit test

### ISSUE THREAD

**Issue by carbontwelve** [thephpleague/route#185]
Hi all, I may be doing something _wrong_ but my unit tests initiate several requests to my application which results in the `dispatch` method of the router being called once for each request e.g first request creates an item in the db, the second request views it.

The issue I am finding is that the `dispatch` method executes `prepRoutes` and that breaks my tests from the second request onwards because the routes had already been preped by the previous "request."

What is the best way to execute multiple dispaches within a single unit test?

**Comment by philipobenito** [comment]
It’s not possible, it’s only designed to be dispatched once, I’d recommend that your tests should only be dispatching once too to reduce test pollution and ensure you’re testing in isolation.

**Comment by carbontwelve** [comment]
You're not wrong. This is a project I am porting from Python to PHP and they had the tests executing a `POST` request to create a particular db record and then executed a `GET` to check the record had been created.

I can do the same with one request that actually tests the end point and then directly pulling from the database to check the record saved is correct.

Thank you @philipobenito for such a quick reply, and thank you for such an easy to use library.
