### ISSUE TITLE
Lazy-load middleware

### ISSUE THREAD

**Issue by XedinUnknown** [thephpleague/route#186]
Was just about to start using this. Even though I feel like it is very bloated, still the features look great.

I wanted my application to be based solely on middleware, and avoid controllers, because I want to force myself to write all functionality in the most re-usable way, and middleware appears to be a good fit. So I write a function that would take a config, and map endpoint + method combination to a middleware pipe. And I understand that I cannot have middleware be lazy-loaded by retrieving it out of the DI container, because [`MiddlewareAwareInterface#middleware()`][] does not accept `string`, which is what the key would need to be.

This is a deal-breaker for me. Other libraries, such as Broker, do this, and it's very convenient. I think this is definitely a feature worth adding.

[`MiddlewareAwareInterface#middleware()`]: https://github.com/thephpleague/route/blob/master/src/Middleware/MiddlewareAwareInterface.php#L16

**Comment by philipobenito** [comment]
I'm open to this, it needs some thought though as probably want to retrieve from the container if there is one. Will get to it some point in the next week or so.

**Comment by philipobenito** [comment]
@XedinUnknown of course :-)

**Comment by shadowhand** [comment]
I would strongly suggest that this be done in a way that allows for strict typing, by having two different classes depending on the resolution type. Dispatching needs the following signature:

```php
public function shiftMiddleware(): ?MiddlewareInterface;
```

The current `MiddlewareAwareInterface` is somewhat awkward, in that it is used in a lot of different contexts and its append methods cannot be strictly typed if both instances and class references are used.

**Comment by philipobenito** [comment]
To keep this strict, I'm going to move this to a `4.x` release, with an additional method `lazyMiddleware`, if a container is available on the matched strategy, it will pull from that, if not, it will just instantiate.

**Comment by shadowhand** [comment]
I have an alternate solution: https://github.com/northwoods/lazy-middleware

Rather than creating a whole separate set of methods to deal with lazy middleware, link to this package and use proxy middleware to handle lazy loading. This ensures that strict typing can be maintained and removes the need to have a PSR-11 container available.

**Comment by philipobenito** [comment]
I don’t think there’s any need to introduce an external dependency. It doesn’t require a container, just uses one if you’re already using one, and planning an improvement for 5.x anyway

**Comment by shadowhand** [comment]
@philipobenito it wouldn't be a dependency of this package, simply a `suggest` for anyone that wants to use lazy instantiation of middleware. Completely bypasses the need to support this functionality here. Less code = less to maintain, and Strict typing is preserved.

**Comment by philipobenito** [comment]
Strict typing is already preserved, and I do like the feature

**Comment by willemstuursma** [comment]
This could also be handled by allowing `iterable` instead of `array` for hinting this. Then, the middlewares could be constructed lazily by a generator.

**Comment by willemstuursma** [comment]
@philipobenito will the interface switch to `iterable` type hints instead of arrays?

**Comment by philipobenito** [comment]
More than likely yes

**Comment by XedinUnknown** [comment]
This issue is closed, but I didn't understand what the resolution is. Could you kindly indicate the conclusion?
