### ISSUE TITLE
Default route arguments?

### ISSUE THREAD

**Issue by tpavlek** [thephpleague/route#19]
Given I have a route `/play/{someusername}` and I want the `someusername` to be optional, is there a supported way of doing this - I'm currently using the Request Response strategy, and the route is just left unmatched when I make a request against `/play` without any arguments.

**Comment by philipobenito** [comment]
Yes, you can create a route for `/play` pointing to the same controller, it's done this way to provide good separation of concerns as in most cases you would be performing different logic within each route

**Comment by philipobenito** [comment]
Closing as answered, can provide more examples if needed, will also be adding a section to the docs on this.
