### ISSUE TITLE
Multiple map()?

### ISSUE THREAD

**Issue by ange007** [thephpleague/route#194]
Hi.
Why was removed option to setup one route for several types of requests?

```php
$router->map( [ 'GET', 'POST' ],  '...', '...');
```

**Comment by shadowhand** [comment]
I would have to assume because it doesn't allow for strict types.

**Comment by philipobenito** [comment]
It was actually to promote separation more than anything. I'm not certain there are any use cases where a separate controller wouldn't be a better option so I'll close this for now but feel free to continue to discuss and I'm open to a change if there is a good enough use case.

**Comment by lautiamkok** [comment]
The good case might be in CORS scenario? Take a look at [Slim's](http://www.slimframework.com/docs/v4/cookbook/enable-cors.html):

```
$app->options('/{routes:.+}', function ($request, $response, $args) {
    return $response;
});

$app->add(function ($request, $handler) {
    $response = $handler->handle($request);
    return $response
            ->withHeader('Access-Control-Allow-Origin', 'http://mysite')
            ->withHeader('Access-Control-Allow-Headers', 'X-Requested-With, Content-Type, Accept, Origin, Authorization')
            ->withHeader('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, PATCH, OPTIONS');
});

...
...
...

/*
 * Catch-all route to serve a 404 Not Found page if none of the routes match
 * NOTE: make sure this route is defined last
 */
$app->map(['GET', 'POST', 'PUT', 'DELETE', 'PATCH'], '/{routes:.+}', function ($request, $response) {
    throw new HttpNotFoundException($request);
});
```

**Comment by zkwbbr** [comment]
I find myself using GET and POST for the same route. For example:

```
$router->get('/foo', Foo::class);
$router->post('/foo, Foo::class);
```
GET is used to render an HTML form
POST is used to process the submitted data

I hope this gets implement in future versions. Thanks.
