### ISSUE TITLE
Documentation: "getting-started" link on the Getting Started page is broken

### ISSUE THREAD

**Issue by jmauerhan** [thephpleague/route#199]
On the Getting Started page, in the "What isn’t Route?" section, there is a link to "getting-started" - this link is broken. I was going to PR a fix but I can't actually figure out what section you intended to link to, as we are already on the Getting Started page, so it wouldn't be super helpful to link to the same page. I would be happy to do a PR to simply remove this sentence if it's left over from a different version of the docs maybe?

**Comment by philipobenito** [comment]
Fixed in #200
