### ISSUE TITLE
JsonStrategy offers no way to log exceptions

### ISSUE THREAD

**Issue by shadowhand** [thephpleague/route#204]
The [current implementation of `getExceptionHandler()`](https://github.com/thephpleague/route/blob/2320c573fa677f5fd65c40c18acf8c9e8720f9ae/src/Strategy/JsonStrategy.php#L118) offers no way to log exceptions that are caught. This is extremely bad for debugging, as there is no way to know what the underlying exception was.

The `JsonStrategy` should probably use PSR-3 `LoggerAwareInterface` and the anonymous class modified to make use of it. Or at least have a `callable $onException` handler that will be triggered when an exception is caught.

Also worth noting that [`Exception` is used](https://github.com/thephpleague/route/blob/2320c573fa677f5fd65c40c18acf8c9e8720f9ae/src/Strategy/JsonStrategy.php#L135) instead of `Throwable`, which means that not all errors are being caught by this middleware.

**Comment by philipobenito** [comment]
Maybe we could add a throwable handler, optionally at first as it’s a breaking change. Then the exception handler can proxy out to the throwable handler. Then we can unify for the next major release.

**Comment by philipobenito** [comment]
Covered by #205
