### ISSUE TITLE
Provide optional functionality to strategies to allow more generic use without the need to create a custom strategy

### ISSUE THREAD

**Issue by philipobenito** [thephpleague/route#205]
This is a proposal to solve raised issues in #201 and #204 

1. Create `AbstractStrategy` and have `{Application,Json}Strategy` extend it.
    - Protected `$defaultResponseHeaders` property, empty array. Structure to follow `'header_key` => `header_value`.
    - `AbstractStrategy::addDefaultResponseHeader(string $key, string $value)` should  add this to the `$defaultResponseHeaders` property. Behaviour should be to allow overriding of anything already existing.
    - `AbstractStrategy::setDefaultResponseHeaders` should accept a key => value array, loop through it and proxy out to `addDefaultResponseHeader` method.
    - `AbstractStrategy::getDefaultResponseHeaders` should just `return $this->defaultResponseHeaders;`.
    - `AbstractStrategy::applyDefaultResponseHeaders(ResponseInterface $response)` should add each of the default headers to the response (only if the response doesn't have an existing header).
    - `AbstractStrategy::{set,get}Logger` should set and get a PSR-3 logger implementation.
2. On construct of `JsonStrategy` invoke `$this->addDefaultResponseHeader('content-type', 'application/json');`.
3. Add functionality to `ApplicationStrategy` to invoke `$this->applyDefaultResponseHeaders();` before returning the response.
4. Refactor functionality existing in `JsonStrategy` to invoke `$this->applyDefaultResponseHeaders();` instead of just dealing with `content-type` before returning the response.
5. Add some logging if a logger instance exists, especially in error handling.
6. Refactor strategies to implement `getThrowableHandler` method and proxy out to that from `getExceptionHandler`, the plan here will be to replace the exception handler with the throwable handler.
7. Refactor the dispatch process to also catch `Throwable` (after `Exception`) and if the method exists on the strategy, invoke the handler, if not let it bubble out to maintain behaviour. Again, the plan here will be to move entirely to `Throwable` in the next major release.

I think that should cover everything for now. Provide any input and either @shadowhand or me will implement soon.

**Comment by shadowhand** [comment]
I'm on it.
