### ISSUE TITLE
Route collection interface is missing parameter/return types

### ISSUE THREAD

**Issue by shadowhand** [thephpleague/route#206]
While the `map()` method uses scalar types, the `get()`, `post()`, etc methods [do not](https://github.com/thephpleague/route/blob/4.x/src/RouteCollectionInterface.php#L26).

Unfortunately, this cannot be resolved without a new major release because adding scalar types to those methods would cause incompatible method signatures for 3rd parties implementing this interface.

_Side note: If the required PHP version was `>=7.2` this wouldn't be an issue due to [parameter type widening](https://wiki.php.net/rfc/parameter-no-type-variance)._

**Comment by philipobenito** [comment]
This is because it extends `RouteCollector` from FastRoute so it can't right now.
