### ISSUE TITLE
MiddlewareAwareInterface could be more strict

### ISSUE THREAD

**Issue by shadowhand** [thephpleague/route#207]
The [`middlewares()` method](https://github.com/thephpleague/route/blob/4.x/src/Middleware/MiddlewareAwareInterface.php#L25) currently takes an array of middleware but there is no type enforcement.

This method could be improved by using a [variadic method definition](https://wiki.php.net/rfc/variadics):

```php
public function middlewares(MiddlewareInterface ...$middlewares)
```

When combined with argument unpacking, it makes it easy to pass an array:

```php
$aware->middlewares(...$arrayOfMiddleware);
```

This can only be implemented in the next major version.

**Comment by philipobenito** [comment]
See #186 relating to this.
