### ISSUE TITLE
MiddlewareAwareInterface has invalid return type

### ISSUE THREAD

**Issue by shadowhand** [thephpleague/route#209]
The [`shiftMiddleware()`](https://github.com/thephpleague/route/blob/4.x/src/Middleware/MiddlewareAwareInterface.php#L41) method cannot ensure that it will always return a middleware. If the stack is empty, [`array_shift` of MiddlewareAwareTrait](https://github.com/thephpleague/route/blob/4.x/src/Middleware/MiddlewareAwareTrait.php#L51) will return `null`.

The correct return type is `MiddlewareInterface|null`, as evidenced by [Dispatcher](https://github.com/thephpleague/route/blob/4.x/src/Dispatcher.php#L55-L59). In fact, this code block cannot ever be executed, because PHP will throw an error when `shiftMiddleware()` returns `null` due to strict types.

I do not believe this can be fixed without a major version change, as it will change the return type of `shiftMiddleware()`.

**Comment by delboy1978uk** [comment]
I found this too. The other option is to grab the array, and if the count is zero throw an exception and catch it where it was called instead? That way the interface won't change and the fix can go in this version.

**Comment by delboy1978uk** [comment]
Thanks @philipobenito :-D
