### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Class 'League\Route\RouteCollection' not found in /.../Providers/AppServiceProvider.php:30

### ISSUE THREAD

**Issue by Benedito0** [thephpleague/route#215]
Stack trace:

- #0

 [internal function]: App\Providers\AppServiceProvider->App\Providers\{closure}()

- #1

 /home/benedito/Documents/INAGBE/auth/vendor/league/container/src/Definition/Definition.php(233): call_user_func_array(Object(Closure), Array)

- #2

 /home/benedito/Documents/INAGBE/auth/vendor/league/container/src/Definition/Definition.php(196): League\Container\Definition\Definition->resolveCallable(Object(Closure))

- #3

 /home/benedito/Documents/INAGBE/auth/vendor/league/container/src/Definition/DefinitionAggregate.php(94): League\Container\Definition\Definition->resolve(false)

- #4

 /home/benedito/Documents/INAGBE/auth/vendor/league/container/src/Container.php(153): League\Container\Definition\DefinitionAggregate->resolve('League\\Route\\Ro...', false)

- #5

 /home/benedito/Documents/INAGBE/auth/vendor/league/container/src/Container.php(169): League\Container\Container->get('League in /home/benedito/Documents/INAGBE/auth/app/Providers/AppServiceProvider.php on line 30

`namespace App\Providers;
use League\Container\ServiceProvider\AbstractServiceProvider;
use League\Route\RouteCollection;
use Zend\Diactoros\Response;
use Zend\Diactoros\SapiEmitter;
use Zend\Diactoros\ServerRequestFactory;

class AppServiceProvider extends AbstractServicePRovider
{
	protected $provides = [
		RouteCollection::class,
		'response',
		'request',
		'emitter'

	];
		public function register()
	{

		$container = $this->getContainer();
		$container->share(RouteCollection::class, function () use($container){
			return new RouteCollection($container);

		});

		$container->share('response', Response::class);

		$container->share('request', function(){
			return ServerRequestFactory::fromGlobals(
				$_SERVER, $_GET, $_POST, $_COOCKIE, $_FILES
			);

		});
	$container->share('emitter', SapiEmitter::class);
	}
}`

**Comment by philipobenito** [comment]
`RouteCollection` was renamed to `Router` in v4.x.

Please refer to the documentation http://route.thephpleague.com
