### ISSUE TITLE
Add optional access to PSR-3 logger in strategies

### ISSUE THREAD

**Issue by philipobenito** [thephpleague/route#217]

**Comment by delboy1978uk** [comment]
what are you looking for for this ticket? just getters and setters for a property?

**Comment by philipobenito** [comment]
Already implemented for next major, hopefully release in the next couple of weeks

**Comment by delboy1978uk** [comment]
Looking forward to it! Will the next major have many BC breaks, or be fairly trivial to upgrade?

**Comment by philipobenito** [comment]
Minimal breaks, but there are a couple, it’s not a rewrite in any way though so should be a trivial upgrade
