### ISSUE TITLE
RouteCollectionInterface::map requires callable not RequestHandlerInterface

### ISSUE THREAD

**Issue by willemstuursma** [thephpleague/route#221]
`\League\Route\RouteCollectionInterface::map` requires a callable and not a `\Psr\Http\Server\RequestHandlerInterface`. I feel this is an oversight in PSR-15 compliance.

I assume this is so that the request handler can be instanciated lazily, but this could also be handled better by a dedicated lazy initializer like https://github.com/northwoods/lazy-middleware.

**Comment by philipobenito** [comment]
No, the route callable itself doesn’t need to me a midlleware, that’s intentional. It does ultimately get wrapped in one though
