### ISSUE TITLE
router not working

### ISSUE THREAD

**Issue by philipnjuguna66** [thephpleague/route#235]
<?php
$router = new \League\Route\Router;
$router->get('/login',(new \App\Controller\HomeController())->login());
$router->get('/',(new \App\Controller\HomeController())->index());

can get to access / route only works  for first load ( i.e. /login)

**Comment by philipobenito** [comment]
You are invoking your controller method rather than defining it. Please see
the docs for how to define route controllers.

**Comment by philipnjuguna66** [comment]
<?php 
$router = new \League\Route\Router;

use Psr\Http\Message\RequestInterface;



$router->get('/login' ,"App\Controller\HomeController::index");
$router->get('/login' ,"App\Controller\DashboardController::index");




$router->dispatch();



that my routes file

**Comment by philipnjuguna66** [comment]
https://route.thephpleague.com/#menu is blank documentation

**Comment by philipobenito** [comment]
Docs are fixed now
