### ISSUE TITLE
What am doing wrong

### ISSUE THREAD

**Issue by philipnjuguna66** [thephpleague/route#236]
![screenshot from 2019-03-07 15-16-26](https://user-images.githubusercontent.com/25553923/53956213-12009b80-40ec-11e9-9a28-18598e58bf11.png)

**Comment by philipnjuguna66** [comment]
![image](https://user-images.githubusercontent.com/25553923/53956258-32c8f100-40ec-11e9-980c-4c3a42e3511c.png)

**Comment by philipobenito** [comment]
I need more info than this. What error are you seeing? What does your
controller look like? It looks like you're rolling your own request object,
are you certain that is doing the correct thing? Are you sending the
response to the browser?

I recommend starting here https://route.thephpleague.com/4.x/usage and
ensuring you understand what is happening then take it from there.

You should also keep in mind that Route is not a framework.

**Comment by philipnjuguna66** [comment]
i understand this is not a framework but routing helper package.  Am getting internal serevr error (500)   
![image](https://user-images.githubusercontent.com/25553923/53957892-a836c080-40f0-11e9-95db-db30c16432e4.png) my HomeControlller
   
![image](https://user-images.githubusercontent.com/25553923/53957949-cc929d00-40f0-11e9-91a8-8ba2930aa532.png)  routes.php
  those are my two files that i am working on

**Comment by philipnjuguna66** [comment]
ERROR NOT FOUND

**Comment by philipobenito** [comment]
If you're using those files then your server must not be setting the
request uri properly

**Comment by Vebolsen** [comment]
I just looked at the source code for `zendframework/zend-diactoros` SapiEmitter has been removed.

**Comment by Vebolsen** [comment]
I think you guys should look into `zendframework/zend-httphandlerrunner`. You can find the documentation here <https://docs.zendframework.com/zend-httphandlerrunner/>. As you can tell it has it's own emitters. You can see them here <https://docs.zendframework.com/zend-httphandlerrunner/emitters/>. Hope this helps solve the issue.

**Comment by Vebolsen** [comment]
When you require `zendframework/zend-diactoros` and `zendframework/zend-httphandlerrunner` your code should look like this.
```php
<?php declare(strict_types=1);

// Require the autoloader.
require __DIR__ . '/../vendor/autoload.php';

use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;

// Create the server request factory.
$request = Zend\Diactoros\ServerRequestFactory::fromGlobals(
    $_SERVER, $_GET, $_POST, $_COOKIE, $_FILES
);

// Create a new router.
$router = new League\Route\Router;

// Map a route
$router->map('GET', '/', function (ServerRequestInterface $request) : ResponseInterface {
    $response = new Zend\Diactoros\Response;
    $response->getBody()->write('<h1>Hello, World!</h1>');
    return $response;
});

// Dispatch the response.
$response = $router->dispatch($request);

// Send the response to the browser
(new Zend\HttpHandlerRunner\Emitter\SapiEmitter)->emit($response);
```
This should fix any issues. Also make sure the files are being autoloaded. This code was tested on php 7.3.
