### ISSUE TITLE
 Class 'Zend\Diactoros\Response\SapiEmitter' not found

### ISSUE THREAD

**Issue by mwz747512353** [thephpleague/route#240]
Error thrown with message "Class 'Zend\Diactoros\Response\SapiEmitter' not found"

Stacktrace:
#1 Error in F:\mewww\onephp\core\lib\App.php:129
#0 onephp\App:start in F:\mewww\onephp\public\index.php:24

**Comment by philipobenito** [comment]
`Zend\Diactoros` has made a change it seems, I've just merged a pull request to update the documentation that references it.

https://route.thephpleague.com/4.x/usage/
