### ISSUE TITLE
Dependency injection link in docs website

### ISSUE THREAD

**Issue by delboy1978uk** [thephpleague/route#242]
Here is the actual link https://route.thephpleague.com/4.x/dependency-injection/

But here on the controllers page 
<img width="808" alt="image" src="https://user-images.githubusercontent.com/2684575/58715735-c6e2e580-83c7-11e9-862d-c347db23003b.png">

It goes here https://route.thephpleague.com/docs/4.x/dependency-injection.md

**Comment by philipobenito** [comment]
would have been easier to find this if you mentioned which page it was on :-)

**Comment by delboy1978uk** [comment]
Oh, sorry if I wasn't clear enough, I did mention the controllers page and included a screenshot ¯\_(ツ)_/¯
