### ISSUE TITLE
Lazy loading controller with wildcard

### ISSUE THREAD

**Issue by jokerham** [thephpleague/route#247]
I have raised a question in stackoverflow about how to set Lazy Loading Controller with wildcard.

https://stackoverflow.com/questions/56763069/how-to-use-wildcard-route-in-league-route-in-lazy-loading-way

I did not get the response. So I checked the source code, but it seems that there is no replacement logic for wildcard in Lazy Loading Controller.

I have changed the source temporarily to resolve this as following by changing Route.php file.

```
    protected function resolveClass(?ContainerInterface $container = null, string $class)
    {
        if ($container instanceof ContainerInterface && $container->has($class)) {
            return $container->get($class);
        }

        foreach ($this->vars as $key => $var) {
            $class = preg_replace("/\{$key\}/", "$var", $class);
        }

        return new $class();
    }

```

**Comment by philipobenito** [comment]
I'm not completely sure what your question is, all routes are already lazy
loaded if you define the controller as a string.

**Comment by jokerham** [comment]
I wanted the controller name to be a string with the wildcard variable as part of the name.

'''router->map('GET', '{module}', "Nanitelink\Module\{module}\{module}Controller::index");'''

As above code, if the request is matched with wildcard "module" I wanted to find the controller by replacing the "{module}" in the controller name.

**Comment by philipobenito** [comment]
No that's not currently possible. It's unlikely that it will be added as a
feature either as the idea with this package was always to explicitly
define routes.
