### ISSUE TITLE
Bug in upgrade from 4.2 to 4.3

### ISSUE THREAD

**Issue by cfinnestad** [thephpleague/route#248]
The dispatcher has an error. works in 4.2 but failed this morning after it updated to 4.3 over the weekend.

Error 
…/vendor/league/route/src/Dispatcher.php92
2
League\Route\Dispatcher setFoundMiddleware
…/vendor/league/route/src/Dispatcher.php44
1
League\Route\Dispatcher dispatchRequest
…/vendor/league/route/src/Router.php112
0
League\Route\Router dispatch
/home/MainApp/AdminPortal/public/index.php41

**Comment by cfinnestad** [comment]
additional info the error is
Call to undefined method Windy\MainApp\Pages\PageStrategy::getContainer()
Our PageStrategy class implements the StrategyInterface which does not require a getContainer() function to be defined.

**Comment by philipobenito** [comment]
Sorry about that @cfinnestad - just pushed a release with a fix here https://github.com/thephpleague/route/releases/tag/4.3.1

Could you confirm the fix when you get a moment then I can close this off?

**Comment by cfinnestad** [comment]
Looks good. No longer getting the error.
