### ISSUE TITLE
Why Router does not implement RequestHandlerInterface?

### ISSUE THREAD

**Issue by PhantomArt** [thephpleague/route#251]
Why `Router` does not implement `Psr\Http\Server\RequestHandlerInterface`?

It will look closer to the standards:

`$response = $router->handle($request);`

**Comment by Juhlinus** [comment]
The dispatcher implements it.

```php
class Dispatcher extends GroupCountBasedDispatcher implements
    MiddlewareAwareInterface,
    RequestHandlerInterface,
    StrategyAwareInterface
```
