### ISSUE TITLE
"Cannot register two routes matching...." on multiple dispatches in same request chain

### ISSUE THREAD

**Issue by destumme** [thephpleague/route#258]
We are using ReactPHP event loop for our microservices (https://reactphp.org/http/) and have been attempting to use the router as a lightweight way to register our controllers/callbacks. We have run into a problem that while the event loop is running, the initial request to the router works without any issues, but any subsequent request fails because on `dispatch` the router is attempting to register the routes a second time.

Most of our index.php. (The symfony kernel is not required, but we are using it for class auto-wiring as well have other entry points for this service that don't use ReactPHP or your Router).

```
$kernel = new \App\Kernel($_SERVER['APP_ENV'], (bool) $_SERVER['APP_DEBUG']); //Symfony Kernel
$kernel->boot();

$router = new Router();

$responseFactory = new HttpFactory();
$jsonStrategy = new JsonStrategy($responseFactory);
$jsonStrategy->setContainer($kernel->getContainer());

$router->setStrategy($jsonStrategy);
\App\Service\RouteRegister::registerRoutes($router);

$loop = React\EventLoop\Factory::create();

$server = new Server(function (ServerRequestInterface $request) use ($router) {
    if (empty($request->getHeader('Content-Type')) || $request->getHeader('Content-Type')[0] !== 'application/json') {
        return new Response(415);
    }

    $response = $router->dispatch($request);
    return $response;
});

$socket = new React\Socket\Server('0.0.0.0:9000', $loop);
$server->listen($socket);

$loop->run();
```

Is there a way to configure this behavior so a single router can handle multiple successive requests? One of the main reasons we want to use the React event loop is to cut down on all the initialization of the Symfony Kernel as well as other routers/etc for a high volume api.

**Comment by harlam** [comment]
Same problem with RoadRunner (https://github.com/spiral/roadrunner)
The reason for the error is in the `prepRoutes` method of the `League\Route\Router` class (if i understand correctly)

```
        /** @var Route $route */
        foreach ($routes as $key => $route) {
            ...
            /* Line 155 */
            $this->addRoute($route->getMethod(), $this->parseRoutePath($route->getPath()), $route);
        }
```

My code:

```
/** @var Router $router */
$router = require_once __DIR__ . '/src/routes.php';
/** @var PSR7Client $psr7Client */
$psr7Client = $container->get(PSR7Client::class);

while ($request = $psr7Client->acceptRequest()) {
    try {
        $response = $router->dispatch($request);
        $psr7Client->respond($response);
    } catch (Exception $exception) {
        $psr7Client->getWorker()->error('Internal server error');
    }
}
```

**Comment by philipobenito** [comment]
This is something that has come up once or twice before, currently everything is designed to be one dispatch per request, I'm planning a release the first week in the new year though and will look to see if this may be feasible for that

**Comment by philipobenito** [comment]
I'm closing this now as housekeeping as I have solved it in the upcoming major release.

**Comment by datashaman** [comment]
Here's a workaround if you can't wait for the next release:
```
<?php

declare(strict_types=1);

namespace App;

use Psr\Http\Message\ServerRequestInterface;

class Router extends \League\Route\Router
{
    /**
     * Prepare all routes, build name index and filter out none matching
     * routes before being passed off to the parser.
     *
     * @param ServerRequestInterface $request
     */
    protected function prepRoutes(ServerRequestInterface $request): void
    {
        $data = array_filter($this->getData());

        if (!$data) {
            parent::prepRoutes($request);
        }
    }
}
```
