### ISSUE TITLE
how to use put or patch or delete method!

### ISSUE THREAD

**Issue by matin-kh73** [thephpleague/route#265]
I wanna use put method for update some data, I used a hidden input with put value and _method name and when I sending a request I faced an error with the method not allow exception!
what should I do?

**Comment by philipobenito** [comment]
That method is a workaround as HTML forms don't natively support PUT/PATCH/DELETE, Route does not handle that for you by default, my suggestion would be to just use POST

**Comment by matin-kh73** [comment]
because of my terms, I have to use it in this way.
Is this package support this workaround?
I try to add the hidden input in the body but finally, I faced the method not allow exception!
regards.

**Comment by philipobenito** [comment]
No, Route doesn't support this by default, you could probably create a middleware to programmatically change the method on the request if that hidden input exists

-------- Original Message --------
