### ISSUE TITLE
Routes in groups - named routes are not generated

### ISSUE THREAD

**Issue by cewlbird** [thephpleague/route#266]
Hi,

first of all thank your for this great lib!
I tried using the group feature within my custom framework.

But I can't generate a named route by using the getNamedRoute method.

**I always get the error** 

> No route of the name (backend.dashboard) exists

As soon as I move this route out of my group it works.
Is this behavior intended or am I doing something wrong?

I guess this issue is related to my problem:  #254 
But there was no answer to this issue.

**Lib Version:** 4.3.1
**My routes definition looks like this (shortened version)**
```<?php
$strategy = (new BaseControllerStrategy())->setContainer($this->container);
$router   = (new Router)->setStrategy($strategy);

router->map('GET', '/', HomeController::class.'::index')->setName('frontend.home');

$router->group('/backend', static function ($group) {
    $group->map('GET', '/', BackendController::class.'::dashboard')
    ->setName('backend.dashboard');
})
->lazyMiddleware(SessionMiddleware::class)
->lazyMiddleware(AuthMiddleware::class);
```
The route frontend.home can be generated without any problems.

Best Regards,

CewlBird

---------------------------------------------------
**EDIT**
I put the Router into your DI Container and it seems to work now when I access the Router from the container. 

But when I pass this router instance as a dependency to another class (to generate routes with parameters) it seems like it gets a completely new instance and all routes are lost again.

---------------------------------------------------
**EDIT2**
I got it now, seems to work so far.
The share param was not set to true, now it works also within other libs.
Sorry, can be closed now!

**Comment by philipobenito** [comment]
Sorry for the late reply, glad you got it working :-)
