### ISSUE TITLE
Possible to set status code when using JSON strategy?

### ISSUE THREAD

**Issue by zkwbbr** [thephpleague/route#267]
According to the [JSON Strategy doc](https://route.thephpleague.com/4.x/strategies/), we can 

> return an array or object, and a JSON response will be built for you.

This is convenient but when using this, is it possible to set the HTTP status code without the need to manually build/return an `ResponseInterface` response?

**Comment by philipobenito** [comment]
Yeah, just return a response object, being able to return an array is just convenience

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by zkwbbr** [comment]
@philipobenito Alright so basically the `array` return convenience method is there for `GET` methods with `200` status only. Anything else must be done the usual way with a proper `ResponseInterface` object.

**Comment by philipobenito** [comment]
Correct, yes. What I tend to do is build a response factory that can create the different responses I need with hypermedia etc when required.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by zkwbbr** [comment]
@philipobenito Got it thanks!
