### ISSUE TITLE
Get detailed error message when using JSON strategy

### ISSUE THREAD

**Issue by zkwbbr** [thephpleague/route#268]
Say you have an undefined variable in your controller handler: e.g., `$foo['bar'];`

Currently when you run this using `JSON strategy`, you'll get something like this:
```
{
  "status_code": 500,
  "reason_phrase": "Undefined index: bar"
}
```
Is there a way for this error message to give more details? E.g., what line number or file the error happens?

**Comment by delboy1978uk** [comment]
why not just extend it and use your own?

**Comment by zkwbbr** [comment]
@delboy1978uk Yeah I ended up using `ApplicationStrategy` instead and customizing from there.

**Comment by philipobenito** [comment]
The base strategies exist only as a starting point and to make it easy for them to be extended with a custom strategy. For example, with the JsonStrategy, I will usually extend that and overload the error handlers for my specific use, but everything else can just pass through
