### ISSUE TITLE
getRoutes() and removeRoute() methods

### ISSUE THREAD

**Issue by delboy1978uk** [thephpleague/route#270]
If we have routes specified in a vendor package which we would like to disable, it would be nice to be able to get the routes registered via a `getRoutes()` method, and a `removeRoute(Route $route)`method to deregister a route.

As an example, imagine a "user" vendor package that has register, login, reset password etc routes, but for a particular site, you don't want people to be able to register an account, so you could remove the route.

https://github.com/thephpleague/route/pull/272

**Comment by philipobenito** [comment]
I honestly don't see a good use case for this, I'd suggest that a vendor package shouldn't be forcing the router you use or setting the routes for you.

**Comment by delboy1978uk** [comment]
my framework is truly modular, you can install vendor packages, and by add that package name to a config file. Then the framework registers all it needs to the DI container. See here for an example https://github.com/delboy1978uk/bone-user/blob/master/src/BoneMvcUserPackage.php#L124-L144

**Comment by philipobenito** [comment]
what I'd suggest instead is something like service providers that are optional to use, it's not ideal to have a vendor do something that needs to be undone so I don't think we should be making that easy

**Comment by delboy1978uk** [comment]
Would you be cool with making $this->routes a protected property in that case? That way your lib stays clean and I can extend it

**Comment by philipobenito** [comment]
It already is 👍 

I'll close this and the PR for now, feedback on your other PR, if you want to look at that I'll get a release out tomorrow

**Comment by delboy1978uk** [comment]
Haha so it is! Okay great! :-P

**Comment by delboy1978uk** [comment]
I'm not seeing any additional feedback for the other pull requests?

**Comment by LuanMaik** [comment]
For this use case, I'll suggest you create a middleware to protect some routes.

**Comment by delboy1978uk** [comment]
@LuanMaik I already have! ;-) Cheers
