### ISSUE TITLE
Expected parameter of type 'League\Route\Strategy\StrategyInterface', 'League\Route\ContainerAwareInterface' provided 

### ISSUE THREAD

**Issue by Wennlys** [thephpleague/route#276]
![image](https://user-images.githubusercontent.com/49328570/77146158-2c908300-6a69-11ea-891d-520fbd6cc312.png)

If I use setContainer on strategy variable, it returns a ContainerAwareInterface value, but setStrategy expects another type of thing. I'm probably using this in the wrong way, but I don't know what.

**Comment by naaando** [comment]
Did you managed to solve? I'm with the same problem

**Comment by naaando** [comment]
Figured out here, the documentation is wrong, the method setContainer don't return the strategy interface like a builder pattern would.
