### ISSUE TITLE
Dispatcher prepended error-middlewares

### ISSUE THREAD

**Issue by pine3ree** [thephpleague/route#279]
Hello, 
I am trying to do this with league/route:
```
server-error-middleware DOWN (will catch uncatched exception)
    forbidden-middleware DOWN (will catch http-403-exception)
        not-found-middleware DOWN (will catch http-404-exception)
            league-router-dispatcher-middleware PROCESS (response or exception)
        not-found-middleware UP (response for http-404-exception)
    forbidden-middleware UP (response  for uncatched http-403-exception)
server-error-middleware UP (response  for any-other exceptions)
```
but the (strategy-aware) dispatcher is prepending another (anon-class) middleware that only throws an exception excluding all the other inner layers. Wouldn't it be better to have stragegies only deal with controller arguments/return value normalizations and let application-defined middleware handle any thrown exception?

kind regards,
maks

**Comment by philipobenito** [comment]
Router is now a `RequestHandler` in `4.4.0` so you can use the router itself as a middleware in another stack
