### ISSUE TITLE
league/route in php long running processes (e.g Swoole)

### ISSUE THREAD

**Issue by pine3ree** [thephpleague/route#280]
Hello, I have tried to use league/route under swoole php server.
The problem is that the router build the routes on every request.
Routes (all the defined routes) should be prepped once and leave untouched and the logic that check for scheme, host, port should perhaps be moved to `Dispatcher::dispatchRequest()` in the `case FastRoute::FOUND:` switch case.
kind regards

**Comment by pfazzi** [comment]
Same problem for me :/

**Comment by pfazzi** [comment]
I solved with this patch:
```php
<?php
declare(strict_types=1);

use League\Route\Router;
use Psr\Http\Message\ServerRequestInterface;

class FixedLeagueRouter extends Router
{
    private bool $routesPrepared = false;

    protected function prepRoutes(ServerRequestInterface $request): void
    {
        if ($this->routesPrepared) {
            return;
        }

        parent::prepRoutes($request);

        $this->routesPrepared = true;
    }
}
```

**Comment by pine3ree** [comment]
Hello @pfazzi,
I believe that this solution may not be enough as it is discarding routes with scheme/host/port that differ from the current request actual values.

https://github.com/thephpleague/route/blob/master/src/Router.php#L133
https://github.com/thephpleague/route/blob/master/src/Router.php#L139
https://github.com/thephpleague/route/blob/master/src/Router.php#L146

For instance if an app supports different host, the only host that will be included in the prepared routes is the fhost of the first request. Same for scheme and port.

kind regards

**Comment by pfazzi** [comment]
Ok, so it's working to me just because I have only one schema/host/port at the moment. Anyway, have you planned to solve this issue?

**Comment by pine3ree** [comment]
Salve @pfazzi,

IMO the logical solution would be to skip those filters when at the prepping step, so that we add all the define routes to the collector, and apply afterwards, when the actual "dispatching" occurs. FastRoute alread filters out by HTTP-method/verb, so the most obvious place would be the FastRoute FOUND case, just to avoid running other route filtering/testing code when FastRoute already decided for a not-matching route.

Cortesi saluti.

**Comment by philipobenito** [comment]
I think this is very much related to #258 which is being looked at for the next major version.

For now, it was not designed to dispatch more than once per request.

**Comment by pfazzi** [comment]
Ok, thanks anyway
