### ISSUE TITLE
subdomain support

### ISSUE THREAD

**Issue by memran** [thephpleague/route#282]
is it possible to configure subdomain routing as like laravel ?

**Comment by philipobenito** [comment]
I don’t know how laravel does it be you can define a route to only match on a certain host, details are in the documentation.

**Comment by memran** [comment]
My intention is something like this.
$router
    ->map('GET', '/acme/route', 'Acme\Controller::getMethod')
    ->setHost('{subdomain}.example.com');

Where subdomain variable will be passed to Acme\Controller::getMethod.

**Comment by philipobenito** [comment]
It just picks up the host based on the request.

**Comment by philipobenito** [comment]
Will close this as matching based on host is already possible
