### ISSUE TITLE
HttpExceptionInterface not extending Throwable

### ISSUE THREAD

**Issue by alanondra** [thephpleague/route#284]
Since `HttpExceptionInterface` does not extend `Throwable`, this actually renders any type-checking requiring `Throwable` for input as incorrect.

For instance `\League\Route\Strategy\ApplicationStrategy::throwThrowableMiddleware()` creates an anonymous middleware that is written to handle `HttpExceptionInterface` but expect `Throwable`.

**Comment by philipobenito** [comment]
The HTTP exceptions are only handled by the JsonStrategy as an easy way to build a JSON response.

If you'd like to use them in a standard application, you could create a custom strategy with custom exceptions.
