### ISSUE TITLE
Add reverse routing info to docs

### ISSUE THREAD

**Issue by garrettw** [thephpleague/route#287]
I'm looking for a router to use for a new project, and this one made it to my short list, partly due to PSR compliance.

~~However, the deal breaker for me is that reverse routing (injecting vars into dynamic routes to generate URIs) doesn't seem to be implemented, and that's something I really need.~~

[Edit] After looking over the code, I see that it actually does what I need already, but this information was nowhere in the documentation. Could that be added?

**Comment by philipobenito** [comment]
Will get to this when I have some time, PR welcome though  if you'd like to contribute

**Comment by philipobenito** [comment]
Thanks, PR merged
