### ISSUE TITLE
Documentation included with installed source code

### ISSUE THREAD

**Issue by ghost** [thephpleague/route#288]
Hi,

Do you consider the documentation must be provided along with the source when installing via Composer? It takes at least 1.4Mio while the source and other files only 66Kio...
I'd love to use league/route for a small project on a tiny hosting (10 MB). I consider removing the `docs` directory from `vendor` is not a good practise.
May I provide a PR to add the `docs` directory to the `.gitattributes` files?

**Comment by philipobenito** [comment]
Added `export-ignore` for them in 5.x release
