### ISSUE TITLE
[Feature] Cached Route

### ISSUE THREAD

**Issue by ncou** [thephpleague/route#289]
Hi,

Nice piece of code. Do you plan to use the cache mechanism already present in fastroute ?

Thanks, keep up the good work.

**Comment by philipobenito** [comment]
Hi, it's not actually possible to use that caching with league/route without ripping out a lot of features, unfortunately, that would take away the reason for league/route to exist, I have a working prototype of a cached router ready to go, I'm just trying to get as much testing in as possible before a release.
