### ISSUE TITLE
JsonStrategy's getThrowableHandler doesn't add default headers

### ISSUE THREAD

**Issue by vixducis** [thephpleague/route#292]
The JsonStrategy implements a getThrowableHandler(), which I personally use to easily handle HttpExceptions thrown from my controllers. The problem I have with the default implementation is that the response from the handler doesn't add the default headers added by addDefaultResponseHeader() (and other methods). The word 'default' for me means that they should be added to every response returned by the strategy. Is there any reason this is not the case?

I know this could be added by a custom strategy or with some middleware, but they're often not-so-clean or cumbersome solutions to something that feels it should be 'default'. So my question: could this be changed or could someone explain the reasoning behind the current implementation?

**Comment by philipobenito** [comment]
Default in this case refers to successful responses.

I wouldn't consider custom strategies as messy, the included strategies are simply a very base level of functionality, I would *always* recommend a custom strategy for anything other than prototyping so that you can build to your specific use case.

**Comment by vixducis** [comment]
I'd argue that in case of an API (which the JsonStrategy is clearly meant for), 'successful' responses and 'unsuccessful' responses are equal citizens and adding default headers are mostly meant to be added to all types of responses. Think of CORS, authentication,... But if there are no plans to change this, I don't have any problems implementing my custom solution and closing this issue.

**Comment by philipobenito** [comment]
There are no assumptions made by the strategies, they're very much meant as starting points, similarly with the ApplicationStrategy handlers, they really need to be extended with functionality you require, you wouldn't want to release an app with that strategy as it is.

Currently no plans to apply defaults to non-2xx responses.
