### ISSUE TITLE
Capture incoming request data

### ISSUE THREAD

**Issue by kellyjoe256** [thephpleague/route#295]
I have been experimenting with this package and I think it is wonderful.

I have a simple index page to handle the routing and it works just fine.

```php
<?php declare(strict_types=1);

use Laminas\Diactoros\ServerRequestFactory;
use Laminas\HttpHandlerRunner\Emitter\SapiEmitter;
use Laminas\Diactoros\ResponseFactory;
use League\Route\Router;
use League\Route\Strategy\JsonStrategy;
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;

$response_factory = new ResponseFactory();
$strategy = new JsonStrategy($response_factory);
/** @var Router $router */
$router = (new Router)->setStrategy($strategy);

$router->post(
    '/hello',
    function (ServerRequestInterface $request): ResponseInterface
    {
        var_dump($request->getParsedBody());
    }
);

$request = ServerRequestFactory::fromGlobals(
    $_SERVER,
    $_GET,
    $_POST,
    $_COOKIE,
    $_FILES
);
$response = $router->dispatch($request);

// send the response to the browser
(new SapiEmitter)->emit($response);

```

My problem is when I send a `POST` request with `JSON` data in it, I am unable to capture it in my code as indicated by the line `var_dump($request->getParsedBody());`.

At the moment, the only way I am able to capture the data sent with the request is by running `json_decode(file_get_contents('php://input'), true);`.

What I do need to do in order to get the payload sent with whatever request, be it `GET`, `POST`, `PUT`, `PATCH`, or otherwise?

Thank you.

**Comment by Zegnat** [comment]
The `getParsedBody()` of a ServerRequest created by `ServerRequestFactory::fromGlobals()` is set to `$_POST` unless something else is provided. By default, that variable will only be filled for form submissions (ie. url encoded / mixed data POST bodies to the server).

You need to parse the posted JSON yourself from the `getBody()`. Alternatively you can [add middleware](https://route.thephpleague.com/5.x/middleware/) that does it for you. An example, [the JSON payload middleware](https://github.com/middlewares/payload#jsonpayload) could be configured to parse the body of all your POST requests automatically and put the result into the parsed body.

**Comment by philipobenito** [comment]
Closed as not an issue with league/route, thanks for the description on how to address this @Zegnat
