### ISSUE TITLE
Host condition is not working in v5.0.1

### ISSUE THREAD

**Issue by gocebonev** [thephpleague/route#298]
In v5.0.1 the host condition is not working. The following code worked ok with 4.5 but throws an error in 5.

```php 
$router->map('GET', '/', ExampleController::class . '::hello')
    ->setHost('test1.com');

$router->map('GET', '/', TestRestController::class . '::hello')
    ->setHost('test2.com');
```

Error: Can not register two routes for '/'.

**Comment by philipobenito** [comment]
Thanks @gocebo I'll look at this asap

**Comment by philipobenito** [comment]
@gocebo sorry for the delay in fixing, seems there was a change in FastRoute, so now I'm pre-checking conditions before mapping routes.

**Comment by philipobenito** [comment]
I've had to make this a 6.x release as it breaks the cached router, another small BC change will come alongside it but it will be a minimal upgrade procedure

**Comment by philipobenito** [comment]
I spoke too soon on it being a BC break, it isn't, so I've tagged 5.1.1
