### ISSUE TITLE
Catch Exception Best Way

### ISSUE THREAD

**Issue by ursoforte** [thephpleague/route#302]
Hi,

I do not found in the [Docs](https://route.thephpleague.com/5.x/) an example to catch the ```NotFoundException``` and ```MethodNotAllowedException``` exception, simple. Without creating new custom strategies. The idea is to use the default ApplicationStrategy.

Someone can add an example code or write an external reference.

How I do with simple route:

The case below is perfect for a simple URL.
```
$router->get('/simple[/]', function (ServerRequestInterface $request): ResponseInterface {
    return new RedirectResponse('/notfound');
});
```
But, when I use custom params like this, and the UUID code is wrong, so I want to redirect the request to NotFound.
```
$router->get('/simple/{param1:uuid}', Controller\Simple::class);
```
Note that I have many HTTP Routes like this, so I don't want to use wildcard routes at all times.

What is the best way to catch exceptions in ApplicationStrategy.
Thanks.

**Comment by philipobenito** [comment]
Application strategy is just a base and should be extended. Otherwise you’d need to wrap the dispatch call in a try catch

**Comment by ursoforte** [comment]
Hi, thank you.
Using the try-catch in dispatch is the way that I don't want to do it. I think something like using the hot way:

```
$strategy->setNotFoundException(new MyNotFoundException);
$strategy->setNotAllowedException(new MyNotAllowedException);
```

**Comment by philipobenito** [comment]
Yeah, I was saying the try catch is your only option if you don’t create a custom strategy. Custom strategy extending application strategy is absolutely the way to go.
