### ISSUE TITLE
I cannot make post requests

### ISSUE THREAD

**Issue by koredalin** [thephpleague/route#306]
Hello Philipo,
I'm to use the League Route 5.
I have installed XAMPP with php7.4.
Whatever I do - all post requests are forbidden for me. I can handle the get requests.
As I have read in internet - it should be because of CSRF security measures. I suppose - I should add a CSRF token in my view template, but the program does not go to the controller. So, the view is not rendered at all.
I'm attaching some pictures of my code. I hope they will help you for faster review.

![LeagueRouteComposer json](https://user-images.githubusercontent.com/6977867/126436696-a275fd7f-0abc-4134-8382-709bafafc2aa.png)
![LeagueRouteIndex php](https://user-images.githubusercontent.com/6977867/126436705-68dee411-4bd2-4268-9532-6e8152c72292.png)
![LeagueRouteRouteFactory php](https://user-images.githubusercontent.com/6977867/126436713-db50e187-5c9b-4f29-b8b2-789645657a0c.png)
![LeagueRouteRoutes php](https://user-images.githubusercontent.com/6977867/126436748-85e406fd-abfb-4c53-8d25-c1102c890b47.png)
![LeagueRouteMethodNotAllowedException](https://user-images.githubusercontent.com/6977867/126436754-a36e969b-aaa9-42ad-bce3-966fca0b371a.png)

Please, help me with an advice.

Thank you
Hristo

**Comment by philipobenito** [comment]
It looks to me like you’re making a GET request to a POST route

**Comment by koredalin** [comment]
Ok - How can I change the request then?
The post request is set in the html form which is not loaded.
What else can I do?

**Comment by philipobenito** [comment]
You need a GET route/request to display the form, then you need the form to submit a POST request to a POST route that will process the form.

These can be separate controllers, or the same, that's up to you, but if you use the same it you will need to do a check to confirm what you need to do based on the incoming method, so I recommend separate controllers.

**Comment by koredalin** [comment]
Very helpful answer, Filipo.
I'll write here where the result.

Thank you!

**Comment by philipobenito** [comment]
I'm going to close this as it's not an "issue" as such, more implementation advice.
