### ISSUE TITLE
Add an option to get the target route from the middleware

### ISSUE THREAD

**Issue by Concentum** [thephpleague/route#317]
Please add an option to get the target route from the middleware, this is necessary to implement authorization in the API when the JWT token contains the user role, and valid permissions for roles are loaded from the configuration.

I think it is wrong to pass the check to the controller

And it also seems strange that middleware does not know for what purpose it is being executed.

I sent a PR.

**Comment by eric-hansen** [comment]
Middleware should just be used for one function, not multiple.  Nor should the middleware need to know what it's purpose is, it should just do it's purpose.

Given your example, a JWT authorization middleware should just check the JWT payload.  Role management is more of a user-level matter, not system-level here.

Another example would be IP filtering.  The middleware shouldn't care what route it's being triggered on, just what the REMOTE_ADDR is and what IPs are (in)valid, thus rejecting appropriately.

**Comment by philipobenito** [comment]
Very much what @eric-hansen said, I've echoed this on the PR and asked a couple of questions to try and steer in the right direction bit no response so these will be closed soon.
