### ISSUE TITLE
psr/simple-cache version constraints 

### ISSUE THREAD

**Issue by arabcoders** [thephpleague/route#320]
Hi,

Im trying to migrate to league/route:^5.0, however it requires "psr/simple-cache": ^1.0 where i depend on ^3.0. is it possible to widen the constraints  to cover all simple-cache versions e.g.:

```json
{
    "psr/simple-cache": "^1.0|^2.0|^3.0"
}
```

**Comment by philipobenito** [comment]
Yeah will sort this after xmas

**Comment by arabcoders** [comment]
> Yeah will sort this after xmas

Thank you and happy holiday to you all.

PS. i can send the PR if you want.
