### ISSUE TITLE
Feature request: Treat Route `$handler` that implements RequestHandlerInterface as callable

### ISSUE THREAD

**Issue by bertramakers** [thephpleague/route#324]
We have an implementation of RequestHandlerInterface for every route in our app. We currently have to register them on the router like this (simplified for example):

```
$helloRequestHandler = new HelloRequestHandler(); // implements RequestHandlerInterface

$router = new Router();
$router->get('/hello', [$helloRequestHandler, 'handle']);
```

Since RequestHandlerInterface is an interface from PSR-15, and this package supports PSR-15 (middlewares), it would be cool if the router could automatically detect the 'handle' method on the request handlers, so we could just register them like:

```
$helloRequestHandler = new HelloRequestHandler(); // implements RequestHandlerInterface

$router = new Router();
$router->get('/hello', $helloRequestHandler);
```

(Or when injecting a dependency container into the router, as a FQN / service name without the `::handle`)

Is this something that you would consider approving if I created a PR for this?

**Comment by philipobenito** [comment]
I like this as an option, I'm currently working on a 6.x release for next week, will add this to my list

**Comment by philipobenito** [comment]
I've implemented this in 6.x release
