### ISSUE TITLE
Feature: Extra map() options

### ISSUE THREAD

**Issue by Visualq** [thephpleague/route#329]
Currently the map function signature is:

`public function map(string $method, string $path, $handler): Route`

It would be nice if we are able to pass some extra options along:

`public function map(string $method, string $path, $handler, array $options = []): Route` 

Or if this is achievable in another way without having to instantiate the handler first?

**Comment by philipobenito** [comment]
What type of options do you think this would be used for?

**Comment by philipobenito** [comment]
Closing for now, but will re-open if a good use case for it is provided
