### ISSUE TITLE
Cannot Change Cache Key

### ISSUE THREAD

**Issue by MrHamel** [thephpleague/route#337]
When implementing my own cache interface which uses Redis, it provides (forces) it's own key, instead of allowing the developer the option of setting their own key. This could be useful in that multiple web apps sharing the same Redis cluster/server do not have to worry about processing the wrong data.

This is what I'm referring to: https://github.com/thephpleague/route/blob/5.x/src/Cache/Router.php#L22

**Comment by philipobenito** [comment]
In 6.x I've updated the caching router to optionally accept a custom key

https://github.com/thephpleague/route/blob/6.x/src/Cache/Router.php#L36

I expect to tag this by Monday 11/11
