### ISSUE TITLE
Is this package still actively maintained?

### ISSUE THREAD

**Issue by andrei-dascalu** [thephpleague/route#338]
Hello,

I mean no disrespect but I see  that latest activity dates roughly 2 years ago, the development (future) 6.x branch seems to be behind the current 5.x and with the release of php 8.3 and deprecation of 8.0 some dependencies in the psr realm have moved forward.

Is help needed here?

**Comment by philipobenito** [comment]
Hi, technically, no, it hasn’t been actively maintained over the last couple of years due to some health issues I’ve been dealing with. However, I’ve slowly been working on major version updates of this and container over the past few months that I’m hoping will get a release in January.

**Comment by andrei-dascalu** [comment]
@philipobenito sorry to hear that :( if there's any assistance needed on the package, I'd be happy to help

**Comment by Humni** [comment]
@philipobenito sorry to hear that too - we also have some capacity to help with minor changes and improvements so feel free to reachout.

**Comment by philipobenito** [comment]
See https://github.com/thephpleague/route/discussions/339
