### ISSUE TITLE
Controller defined as Lazy Loaded Array Based Callable (Proxy) does not work anymore in 6.0.0

### ISSUE THREAD

**Issue by micheloe** [thephpleague/route#347]
In Route 6.0.0, when defining routes to a controller using the lazy loaded array based callable (proxy), the following PHP Fatal error is triggered:

`Uncaught TypeError: League\Route\Router::post(): Argument #2 ($handler) must be of type callable|string, array given`

or, when defining a route via a `RouteGroup`:

`Uncaught TypeError: League\Route\RouteGroup::post(): Argument #2 ($handler) must be of type callable|string, array given`

The definition of this type of controller is described here: https://github.com/thephpleague/route/blob/6.x/docs/6.x/controllers.md#lazy-loaded-array-based-callable-proxy.  This is caused by the type hint change in da65872725af481d65f8f16552e68e33fdfae5ca in the `RouteCollectionTrait` component.

An example definition of such a route:
```php
$router->map('GET', '/', [Acme\SomeController::class, 'someMethod']);
```

Changing it to a lazy loaded class method (proxy) as described [here](https://github.com/thephpleague/route/blob/6.x/docs/6.x/controllers.md#lazy-loaded-class-method-proxy) works around this issue. An example definition of such a route:
```php
$router->map('GET', '/', 'Acme\SomeController::someMethod');
```

**Comment by philipobenito** [comment]
Will take a look tomorrow, can't remember if it was defined behaviour not to resolve it unless it was registered with a container.

Sent from Proton Mail Android

-------- Original Message --------

**Comment by micheloe** [comment]
Thanks! FWIW, the controller class name is defined on the container, so the router is able to resolve the specified class as string via the container.

**Comment by philipobenito** [comment]
@micheloe good catch, was a side effect of introducing type checks, fixed here: https://github.com/thephpleague/route/commit/1926646cd44659c3f1ce2ea7bc4bf018fcd823a1

Will tag 6.1.0 shortly

**Comment by philipobenito** [comment]
Tagged https://github.com/thephpleague/route/releases/tag/6.1.0

**Comment by carlrafting** [comment]
It seems `League\Route\Router`, `League\Route\RouteCollectionTrait` and the `League\Route\RouteCollectionInterface` still use `string|callable` signature for `$handler`. Should those be updated as well?

I have pretty much the same use case as @micheloe, but perhaps i should clarify the details.

In my case, i have a php file where i declare all my application routes. I use dependency injection with `league/container` for passing in an instance of `Router`.

```php
<?php

/* config/routes.php */

return static function (League\Route\Router $router) {
  $router->get('/', [Acme\Controller::class, 'index']);
};
```

This setup will give me the following PHP error on `v6.1`.

```
Fatal error: Uncaught TypeError: League\Route\Router::map(): Argument #3 ($handler) must be of type Psr\Http\Server\RequestHandlerInterface|callable|string, array given, called in C:\path\to\config\routes.php on line 13 and defined in C:\path\to\vendor\league\route\src\Router.php on line 120
```

**Comment by philipobenito** [comment]
Haha, I just moved the problem then, watch out for 6.1.1 shortly.

Thanks

-------- Original Message --------

**Comment by carlrafting** [comment]
Great! Looking forward to 6.1.1. 🙂

**Comment by philipobenito** [comment]
Okay that should be fully sorted now @carlrafting - if you're in that area, a confirmation of fix would be very much appreciated.

I'm rewriting the end-to-end tests so will account for this to ensure parity in future.

**Comment by carlrafting** [comment]
I can confirm that everything works as expected with 6.1.1. Thanks for looking into it, and resolving the issue. Kudos! 🎉

**Comment by micheloe** [comment]
I can confirm 6.1.0 still contained the error and 6.1.1 does indeed fix this issue. Thanks!

**Comment by philipobenito** [comment]
Excellent! Thanks guys
