### ISSUE TITLE
Dependency issue in PHP 8.4.1: Implicitly marking parameter $options as nullable is deprecated

### ISSUE THREAD

**Issue by jonaskohl** [thephpleague/route#348]
When upgrading my project to the newly released PHP 8.4.1, the following warning will be emitted via the [`opis/closure`](https://github.com/opis/closure) dependency:

    Deprecated: Opis\Closure\unserialize(): Implicitly marking parameter $options as nullable is deprecated, the explicit nullable type must be used instead

As the latest version and latest commit of `opis/closure` were both almost 3 years ago, it is safe to assume that library is abandoned and should be removed/replaced as a dependency from this project.

**Comment by philipobenito** [comment]
Yes it looks that way, I'm planning to fork in to route when I get a moment, probably over the weekend or on Monday.

-------- Original Message --------

**Comment by jonaskohl** [comment]
Way ahead of you. I already implemented a fix and opened a pull request over at opis/closure/pull/144.
It's literally a one-character fix :smile: (one missing `?`).

**Comment by jonaskohl** [comment]
As per https://github.com/opis/closure/pull/144#issuecomment-2493967712 there is a replacement library by Laravel: [laravel/serializable-closure](https://github.com/laravel/serializable-closure)

**Comment by philipobenito** [comment]
Oh excellent, I'll replace it over the weekend.

-------- Original Message --------

**Comment by philipobenito** [comment]
@jonaskohl https://github.com/thephpleague/route/releases/tag/6.2.0

thanks for finding the replacement
