### ISSUE TITLE
Better implementation of route parameters for RequestResponseStrategy 

### ISSUE THREAD

**Issue by nebulousGirl** [thephpleague/route#35]
The Request object from Symfony has a built-in property (attributes) for parameters from the route:
http://api.symfony.com/2.6/Symfony/Component/HttpFoundation/Request.html#createFromGlobals%28%29

The RequestResponseStrategy would have to be modified like this:
```
    $request = $this->getContainer()->get('Symfony\Component\HttpFoundation\Request');
    $request->attributes->add($vars);
    $response = $this->invokeController($controller, [
            $request,
            $this->getContainer()->get('Symfony\Component\HttpFoundation\Response')
      ]);
```

What are your thoughts on this? I can do a pull request later for this if you want.

**Comment by philipobenito** [comment]
Symfony HttpFoundation is actually being dropped for v2 in favour of PSR-7, however, there will be a similar type of support for this via the message interfaces.

**Comment by nebulousGirl** [comment]
Glad to hear it, when is v2 expected to be released? I'll use my fork for the time being.

**Comment by philipobenito** [comment]
Aiming for 2-3 weeks from now, it's dependent on some other work going on with league/container

**Comment by philipobenito** [comment]
@nebulousGirl would you be interested in doing a PR for this for the current v1 branches? I think it certainly has merit but is not really prudent to v2 as HttpFoundation will not be a hard dependency.

**Comment by nebulousGirl** [comment]
@philipobenito I will look into that over the weekend. I can also implement the Request::createFromGlobals if the request was not already registered to the container, I saw it in another issue. 

Have you looked into PSR7 implementations yet? Are there any interesting ones?
