### ISSUE TITLE
Separate different args with other characters than "/"

### ISSUE THREAD

**Issue by floffel03** [thephpleague/route#39]
Is there a way to have more than one variable inside of one part of a url?

Something like this doesn't work for me:

```
$router->addPatternMatcher('wordStartsWithM', '(m|M)[a-zA-Z]+');
$router->addPatternMatcher('wordStartsWithQ', '(m|Q)[a-zA-Z]+');

$router->get('/test/{first:wordStartsWithM},{second:wordStartsWithQ}', function (Request $request, array $args) use ($mysqli) {
        return ["This is just for debug" => "true", "first" => $args['first'], "second" => $args['second']];
});
```

My code above generates the following result for me:
```
[[]]
```

But it 'seems' like the routing is working, partially... Am I doing it wrong?

**Comment by philipobenito** [comment]
I'm a little confused about the use case. Unfortunately there is no way to use multiple pattern matches within the same URI segment

**Comment by floffel03** [comment]
In my special case I thought about a google-maps-style api use case, to have an request uri like this:

https://www.google.de/maps/search/@48.9174128,11.4079934,7z
https://www.google.de/maps/search/@lat,long,somenumber

Okay, I'll be honest: I don't know any other use cases at the moment (except splitting up too big regular expressions or something)...

I think I don't have the time (and knowledge at the moment) to implement it my self, so if it is too specified for you... please close this issue for me :)

**Comment by philipobenito** [comment]
If you send me an email I'll help you build a regular expression to suit your needs when I have time. philipobenito [at] gmail.com
