### ISSUE TITLE
Stop requiring a container

### ISSUE THREAD

**Issue by shadowhand** [thephpleague/route#40]
There's no particular reason that `league/container` is a hard dependency, as it is only required when using the "Class Method" type of dispatching. Instead of being a required dependency, it should be suggested. This would make it possible to avoid using `league/container` completely for those of us that prefer a different DI implementation.

**Comment by philipobenito** [comment]
Currently it is a hard dependency as DI is a big part of the strategy functionality but this is being looked at for possibly splitting out in v2.

**Comment by shadowhand** [comment]
I have to disagree with this, because [it is only optional in AbstractStrategy](https://github.com/thephpleague/route/blob/55493a3725c8cf6092d42a96bd43ac7b35d40b15/src/Strategy/AbstractStrategy.php#L49-L52).

**Comment by philipobenito** [comment]
Every class based controller is built via the container when using the strategies provided, so, yes it is currently a big part of the dispatch process, however, as I said, it is looking likely that the strategies will be split out, therefore allowing the container dependency to be moved to the strategy.

**Comment by shadowhand** [comment]
Exactly my point... it is only necessary when you use a classes as part of the strategy. Implementing a custom strategy allows me to avoid the container completely, but I cannot avoid having it installed. Hence, it should be suggested only.

**Comment by philipobenito** [comment]
This would be a breaking change to the package as a whole so it cannot be removed for v1, however, as the package allows you to do as you wish without using the container you are not required to use it. As stated, it's being reassessed for v2.
