### ISSUE TITLE
Broken link in MethodArgumentStrategy docs

### ISSUE THREAD

**Issue by FLamparski** [thephpleague/route#41]
The link to "League\Container" is missing a 'u' in 'thephpleague'. Page: http://route.thephpleague.com/method-argument-strategy/

Current: https://github.com/thephpleage/container (404)

What it should be: https://github.com/thephpleague/container

**Comment by hannesvdvreken** [comment]
Fixed. Can be closed now. Thanks for reporting!

**Comment by FLamparski** [comment]
No problem, glad I could help.
