### ISSUE TITLE
How exactly do I use League\Container\Container w/ this lib?

### ISSUE THREAD

**Issue by G4MR** [thephpleague/route#43]
So I noticed in the docs it says you can set a custom container and pass it to the constructor of the route collection.  There's no way to actually access the container from the route collection class though?

So what exactly is the point in passing a new container to the routecollection class?  Maybe there's some confusion because the docs are vague on the usage and I can't seem to find anything anywhere questioning it.

**Comment by hannesvdvreken** [comment]
Basically the container is injectable because it makes the routecollection class testable. Injecting the constructor through the constructor is a design pattern called **dependency injection** (and more specifically **constructor injection**). There's no reason why you should try to access the container through the routecollection. 

If someone decides to create a more efficient container, they can adhere to the same interface and let the routecollection use it. All optional but nonetheless possible.

**Comment by philipobenito** [comment]
@G4MR Just for a little further clarification, the idea is that the container would be instantiated and configured before you pass it in to the route collection then your controllers can be resolved via the container allowing them to use dependency injection throughout your application. If you any reason you need to access the container after it has been passed in then just interact with the variable that you attached the container to before it was passed in and the changes will persist as PHP deals with objects by reference.

**Comment by G4MR** [comment]
@philipobenito You create a new route collection and optionally pass your already created DI container to it else RouteCollection will create one anyways.  Then you set your routes and choose your strategy.  Once you dispatch what ever strategy is chosen, assuming the default RRS, then the dispatcher handles handleFound if found and allows the strategy to do:

    protected function invokeController($controller, array $vars = [])
    {
        if (is_array($controller)) {
            $controller = [
                $this->getContainer()->get($controller[0]),
                $controller[1]
            ];
        }
        return call_user_func_array($controller, array_values($vars));
    }

right, well what happens here if the container doesn't contain the class/method?  It just reflects the class automatically I'm assuming since the container has those tools it's sort of a convenience?  Then I guess if container already had said definition it'll attempt to grab it else you're using the container as a tool to reflect class recreation?  Wondering if I understood everything correctly and that's the only reason for passing the container?

**Comment by philipobenito** [comment]
Yes that's correct for the class based strategies. If the container is empty it will attempt to reflect on the constructor and inject any arguments. If there is no constructor or no arguments to be passed, the class will just be instantiated as normal.
