### ISSUE TITLE
Upgrade to latest version of Container

### ISSUE THREAD

**Issue by Mike724** [thephpleague/route#45]
I don't believe withMethodCall is part of Container v1.0 (which is currently required for this component). A solution to this would be upgrading to the latest version of Container.

**Comment by philipobenito** [comment]
That method has always been part of the definitions within container. Are you having a specific problem?

**Comment by Mike724** [comment]
Huh, it seems to just be a PhpStorm issue (withMethodCall not in the autocomplete, plus gives warning). Lesson learned: don't trust PhpStorm all of the time.

Thank you for the awesome work on this component!

**Comment by philipobenito** [comment]
Not a problem, the issue here I think comes from that fact that the `withMethodCall` method is not within the `Container` class but within a different class that is returned by the `add` method so an IDE may not pick up on this.
