### ISSUE TITLE
Route prefixes/prehandlers

### ISSUE THREAD

**Issue by outrunthewolf** [thephpleague/route#46]
Not so much of an issue as a question.

Is it possible to implement the following like laravel:

```php
Route::group(['domain' => $domain, 'prefix' => 'version1'], function() {});
```

I was thinking strategies might help with this, but i'm not 100% sure how to. Any advice on where to look would be great! 

Thanks.

**Comment by philipobenito** [comment]
What is the intended outcome of the example you've given? So that you can have a set of routes that are automatically prefixed etc? Such as versioning an API?

**Comment by outrunthewolf** [comment]
Yeah basically.

domain - checks any requests are being served under the correct server name.
prefix - prefixes any sub routes with that string, i.e. v1, beta, etc...

prefix would be handy, but I suppose there are other ways around it. What I'm looking for really is a pre-route handler call, or function I can tie into.

So once a route matches I can check a few other things like are you authorised for that route, have you passed the correct prefix, once they've passed that check I can route them to the actual function or class that is associated with that route.

**Comment by philipobenito** [comment]
Well this is definitely something that could be implemented via a strategy, but also something I'm going to think about through development of v2 over the next couple of weeks so if it's not urgent, I can involve you in that process once I get to it.

**Comment by philipobenito** [comment]
Groups picked up as part of `2.0.0`

**Comment by outrunthewolf** [comment]
:+1: awesome
