### ISSUE TITLE
[League/Route] - Request Object inside Controller (using Class Methods) is empty?

### ISSUE THREAD

**Issue by 7php** [thephpleague/route#48]
Hi,
I have this code setup, I'm using symfony http request, but for routing/dispatching I'm using League/Route for a change..
I note something:
in the controller method (example below quoted), the $request object is empty - is this normal? Because I would expect that the initial $request object obtain (Request::createFromGlobals()) should have been reflected to Request in: public function action (Request $request, Response $response)
But this does not seem the case and the parameter being there is not having any use - defeating the purpose.

I am surely missing something here, anyone can help?
```
use Symfony\Component\HttpFoundation\Request; 
use Symfony\Component\HttpFoundation\Response; 

class MyController 
{ 
    public function action (Request $request, Response $response) 
    { 
        print_r($request); // everything is empty including paramter bag for a POST !!
    } 
}
```

**Comment by philipobenito** [comment]
Hey @7php, this has been the subject of some discussion lately as the strategy assumes that a request is already set up, it's something that is being addressed in a currently open pull request but for now, you will need to add a request to the container somewhere within your bootstrap.

If you need any guidance with this, just give me an email :-)

**Comment by hannesvdvreken** [comment]
The pull request mentioned is #47

**Comment by 7php** [comment]
Hey guys thanks for the response.
Ok, yes right now that's what I'm doing, passing it to the container.

cheers

*-----*

*///Yours 7PHPly,-(Khayrattee Wasseem**)*
*{*
*    Twitter  =>  @7php <http://twitter.com/7php> *
*    More..   =>  about.me/khayrattee <http://about.me/khayrattee>*
*};*
