### ISSUE TITLE
New container is not saved in strategy

### ISSUE THREAD

**Issue by sagikazarmark** [thephpleague/route#49]
https://github.com/thephpleague/route/blob/master/src/Strategy/AbstractStrategy.php#L36

The new container is returned but not saved. Also, `ContainerAwareTrait` could be used here.

**Comment by philipobenito** [comment]
:+1: will pick this up this week, will just be using the trait, therefore enforcing the setting of the container to retrieve.

**Comment by sagikazarmark** [comment]
I think you can override the getter to create a default container if none
available. That's a good feature, but you also have to store the new
container.

**Comment by philipobenito** [comment]
Fixed by using the trait
