### ISSUE TITLE
Support container-interop

### ISSUE THREAD

**Issue by mwillbanks** [thephpleague/route#52]
Currently route requires league/container, however, it would be beneficial to support the container-interop project as to not create a hard dependency on the league/container project itself.  I for one would prefer to utilize a supporting container-interop project instead in some cases.  I believe that is a planned feature for league/container but ideally it would happen with v2 of container and the dependency would be lifted in v2 of route.

**Comment by sagikazarmark** [comment]
Container Interop is started to be a PSR. I think that should be released first. Using container interop and then changing to the PSR is also a breaking change.

**Comment by philipobenito** [comment]
This isn't something that's planned around the current release schedule but will be looked at as and when a PSR is accepted.
