### ISSUE TITLE
league/pipeline integration

### ISSUE THREAD

**Issue by SignpostMarv** [thephpleague/route#56]
I'd like to see some integration with pipeline for modifying Response objects to assist with the purposes of (but not limited to)
* Perhaps using Intervention for on-the-fly WebP encoding
* Auto-adding headers (HSTS, X-Frame-Options, CORS etc.)
* Handling PSR-7 Response objects
* Using hooking into external or PHP-based compilers for less/sass/es6 etc.

Not suggesting that those be baked in, but if league/pipeline were to be integrated, those are the examples I'd like to see (except maybe that last one, I've yet to find a PHP-based less compiler that's fully feature matching).

**Comment by hannesvdvreken** [comment]
Funny that you mention this. I experimented with that this week and found that pipeline is useful for this, but requires you to make 2 separate pipelines. 1 for request processing, 1 for response processing. The use of a stack of middlewares is more useful for that (like stackphp and guzzle v6).

I'm in the process of creating a package for that and will release it shortly and propose it to the php league. I will also release a league/route middleware shortly after. So it will all be compatible, but extendible and 100% decoupled by only depending on psr/http-message.

**Comment by philipobenito** [comment]
This is definitely something I'd like to see and if @hannesvdvreken is working on something I won't duplicate the work but I definitely think it does belong as a separate package.

:+1:
