### ISSUE TITLE
Error while implementing Custom Strategy

### ISSUE THREAD

**Issue by jishcem** [thephpleague/route#59]
First of all, thanks for this fantastic package. 

I was trying to implement a login and sort of a middleware to filter unauthenticate route requests. 

So I use the Custom Strategy mentioned in the documentation. 

I am not sure what code to put in the dispatch method. But, when I copy the code of RequestResponseStrategy's dispatch method, it did not show any errors. 

But, in one Post request route - this error showed up - "Warning: array_map(): An error occurred while invoking the map callback in vendor\league\container\src\Container.php on line 495"

I am in the dark what to do next in this case. 

Can you help me out to replicate the functionality if there is no Strategy used at all for the RouteCollection - so that I can have the same code in CustomStrategy's dispatch method ?

**Comment by philipobenito** [comment]
Are you able to provide a gist with the code you are using please? Including the controller and middleware you are using.

**Comment by jishcem** [comment]
Here is the gist. 

https://gist.github.com/jishcem/e8febe0ce2d2146e690e

**Comment by jishcem** [comment]
Forgot to mention about the Middleware - its just a code that is intended to check session and redirect to login :) Even without that middleware I got this error.

**Comment by philipobenito** [comment]
Commented on the gist, however, I think you'd be better off using the `RequestResponseStrategy`, the only enforcement is that you must return the request object from your controller.

**Comment by philipobenito** [comment]
I'll close this issue as it's not actually a bug but about implementation, can continue discussion on here or the gist though.
