### ISSUE TITLE
addRoute signature not according to parent class

### ISSUE THREAD

**Issue by hannesvdvreken** [thephpleague/route#62]
in develop branch:

Strict standards: Declaration of League\Route\RouteCollection::addRoute() should be compatible with FastRoute\RouteCollector::addRoute($httpMethod, $route, $handler)

**Comment by philipobenito** [comment]
Wanna PR this against `1.x`? I can pick it up soon if not

**Comment by hannesvdvreken** [comment]
It has always been like that, but PHPSpec fails to run in a project that depends on league/route if it doesn't match. There is no change possible without breaking changes to make this match the parent interface.

**Comment by philipobenito** [comment]
It's only a var name isn't it? Arg order is correct?

**Comment by philipobenito** [comment]
Ah, extra param too :-( it's ok for v2 as I'm no longer overloading

**Comment by hannesvdvreken** [comment]
:+1:
