### ISSUE TITLE
Named Routes

### ISSUE THREAD

**Issue by 7php** [thephpleague/route#68]
Hi, I'm not sure if this is implemented yet. Would be cool to have named routes.

**Comment by philipobenito** [comment]
Already in

**Comment by 7php** [comment]
is it documented somewhere already? (would like to see syntax - thanks)

**Comment by philipobenito** [comment]
No, documentation isn't written yet but chain setName('name') on to any
mapping of a route.

**Comment by 7php** [comment]
I've tried chaining, but get the following error:
**Fatal error: Call to undefined method League\Route\RouteCollection::setName()**

I'm using v1.2.3
Code sample:
```
public static function getRoutes(ContainerInterface $container)
{
    $routes = new RouteCollection($container);
    $routes->addRoute('GET', '/index', 'Controller\IndexController::index')->setName('welcome');
    //or even:
    //$routes->get('/index', 'Controller\IndexController::index')->setName('welcome');
    return $routes;
}
```

Anything I'm missing?

**Comment by philipobenito** [comment]
They're only available in v2, its not possible in v1

**Comment by 7php** [comment]
ah! ok :)

Any time frame for the arrival of v2?

Thanks Phil, I think that's it for me for today :)
Thank you for everything and for all you do!

cheers!

**Comment by philipobenito** [comment]
Hoping to have it tagged and documented by tomorrow or Monday :-) if you
enjoy a code dive, the develop branch is very close to finished

**Comment by 7php** [comment]
yes sure, will keep an eye on the develop branch
