### ISSUE TITLE
Handling trailing slashes by default

### ISSUE THREAD

**Issue by 7php** [thephpleague/route#70]
By default, trailing slashes are not handled - can this be **IN** by default please?

Example:
**/page** and **/page/** should both be OK if only **/page** was added in RouteCollection

**Comment by philipobenito** [comment]
Route won't handle both by default as you shouldn't as you shouldn't, it
causes inconsistencies and can lead to Google seeing duplicate content,
however, if you really want to do that it's very easy to do so in your
bootstrap.

**Comment by 7php** [comment]
"Google seeing it as a duplicate content" is not an acceptable answer please. Handling duplicate content forms part of a strategy, namely an "seo strategy", and not the task of "coding framework", example using rel="canonical" (REF: https://support.google.com/webmasters/answer/139066?hl=en)

Other frameworks have it, so I don't see why we can't have it "by default" - give it another thought ;)

Keep up the good work!

**Comment by philipobenito** [comment]
I'm sorry by it won't be handled by default.

As this is not a framework but a tool we can't make assumptions about what
is being built, however, as I say, it can easily be implemented with a
quick trim of the path on the request.

**Comment by 7php** [comment]
sure, fair enough - noted.

Can you confirm if this is trailing process looks good enough:
```
$pathInfo = $request->getPathInfo();
$replacement_count = 1;
$pathInfo = str_replace('/?', '?', $pathInfo, $replacement_count);
$pathInfo = rtrim($pathInfo, '/');

//and then, something like:
$response = $dispatcher->dispatch($request->getMethod(), $pathInfo);
```

**Comment by philipobenito** [comment]
If you register all of your routes without a trailing slash then you can simply do the following:

```
$pathInfo = rtrim($request->getPathInfo(), '/');

// ...

$response = $dispatcher->dispatch($request->getMethod(), $pathInfo);
```

It will change with v2 but I will document it.

**Comment by 7php** [comment]
yes correct, I've just tested this.

Btw when you say change, what kind of them? :) Hope it's not a very big change.. Yes please do document.
thanks.

**Comment by philipobenito** [comment]
Well its PSR-7 compatible so it will just accept a request and a response
to dispatch, this way its a compatible middleware too.

**Comment by maartenscholz** [comment]
A way todo this in v2:
```
$container->share('request', function () {
    $request = Zend\Diactoros\ServerRequestFactory::fromGlobals(
        $_SERVER, $_GET, $_POST, $_COOKIE, $_FILES
    );

    return $request->withUri($request->getUri()->withPath(rtrim($request->getUri()->getPath(), '/')));
});
```

**Comment by hannesvdvreken** [comment]
Hi Maarten,

You can use `Zend\Diactoros\ServerRequestFactory::fromGlobals();`, no need to pass them.

**Comment by maartenscholz** [comment]
I see, thanks Hannes!

Updated the examples.

**Comment by Arcesilas** [comment]
For the records (I found this issue because I wanted to solve the same problem), another solution (which I consider better, since it prevents duplicate content), with Zend Diactoros:

```php
use Zend\Diactoros\Response\RedirectResponse;

$router->get('/{any}/', function (ServerRequestInterface $request, $any) {
    $redirect = rtrim($request->getUri(), '/');
    return new RedirectResponse($redirect, 301);
});
```

It can be adapted to add a trailing slash if you prefer. I think the route should then be added last.

**Comment by philipobenito** [comment]
Just to be clear, Route no longer allows direct passing of the path info. But there is no need to implement a code solution to this, you can simply define one or the other and have your webserver force or strip the trailing slash.

**Comment by Arcesilas** [comment]
Actually, it's the only way I found to force urls without trailing slash... I don't understand what you mean by *you can simply define one or the other and have your webserver force or strip the trailing slash*

**Comment by Arcesilas** [comment]
Yeah I was still thinking with PHP built-in server... I guess I need some sleep.
