### ISSUE TITLE
Question about the use of v2

### ISSUE THREAD

**Issue by Qathom** [thephpleague/route#74]
First of all, thank you for sharing your amazing router!

I couldn't find any examples to use the v2, so I wonder if you can give me one.
Furthermore, PSR7 will be use?
What kind of PSR7 module do you recommend, if any?

I am in a hurry to use the next version in one of my project because the next version looks pretty better than the first release and I am searching a powerful router!

Thank you :)

**Comment by philipobenito** [comment]
There is an example simple bootstrap process at the bottom of the 2.0.0 RC pull request #73. For convenience, the link is below, this example uses Zend Diactoros (https://github.com/zendframework/zend-diactoros) as the PSR-7 implementation.

Example:
https://packagist.org/packages/league/route#2.0.0-RC1

Documentation should follow over the next few days.
