### ISSUE TITLE
.htaccess guide

### ISSUE THREAD

**Issue by emabusi** [thephpleague/route#76]
I am having a problem setting this up as there is no documentation of the location of the .htaccess in a project and data that should be in the .htaccess file

**Comment by philipobenito** [comment]
Your htaccess completely depends on how you set up your project and environment.


Unfortunately this is beyond the scope of this project as it does not make any assumptions about those decisions as this project is not a framework.




However, there will be other projects popping up similar to Proton that put Route in to a more framework specific mindset.

**Comment by emabusi** [comment]
Thanks for your response @philipobenito kindly see http://stackoverflow.com/questions/33066070/htaccess-for-custom-url-routing-using-thephplegue-route on the problem I am facing. I will glad to get your assistance.

**Comment by philipobenito** [comment]
I have posted an answer to your question on SO.
