### ISSUE TITLE
Nested Routes in 2.0

### ISSUE THREAD

**Issue by kayladnls** [thephpleague/route#79]
Have you considered adding this feature? If it's something that you'd like to see added I could start working on a PR. I know it would be helpful for the work we're doing.

**Comment by Eragon666** [comment]
Isn't that the same as #46?

**Comment by philipobenito** [comment]
@kayladnls is this something that route groups covers? I know we discussed it but it was a while ago.

**Comment by philipobenito** [comment]
I'll consider this as complete as I understand it. There is #96 that is also similar.
