### ISSUE TITLE
PSR-7 support in 2.0

### ISSUE THREAD

**Issue by KorvinSzanto** [thephpleague/route#80]
Is there any way to sneak PSR-7 diactoros default support in the 2.0.0 release? We can suggest the symfony bridge and the symfony/http-foundation to make it simple to support. If so, I'd be happy to do this work.

**Comment by kayladnls** [comment]
If I'm not mistaked, the symfony/http-foundation support is dropped for 2.0 in favor of Diactoros.

**Comment by KorvinSzanto** [comment]
Thanks Kayla!

**Comment by philipobenito** [comment]
@kayladnls is correct, support is on PSR-7 abstractions so any implementation will work.
