### ISSUE TITLE
Setting a custom Dispatcher

### ISSUE THREAD

**Issue by rmrhz** [thephpleague/route#82]
As we can set custom strategies. It might be a good implementation in setting a custom dispatcher or try to interface it. So it will possible to do what in this issue #25 has stated. I'm working on adapters in which I can replace route components with ease without rewriting code every time.

**Comment by philipobenito** [comment]
The dispatcher is opinionated mainly because it's an extension to FastRoute, this isn't something that can happen for the upcoming v2 but it will be reevaluated for the next major release.
