### ISSUE TITLE
league/container 2.x dependency version conflict

### ISSUE THREAD

**Issue by cryode** [thephpleague/route#83]
I added `league/container:^2.0` as a dependency to my project on its own, then attempted to add `league/route` as well (simply via `composer require league/route`), and I receive a conflict due to Route requiring `league/container:~1.0`.

I can eliminate the Container requirement so it will fall back to 1.0 resolution, but that's not ideal as I'd like to use the latest version of these packages. I know that Route 2.0 is around the corner sometime (and my project is slow moving, so I don't really care about fixing this immediately). Just figured I'd give you a heads up.

As someone who is starting to put individual components together to try and build an ideal "framework" for my projects, I'm happy to put some of these components through their paces and provide feedback and use where necessary, if I can be of any help.

Cheers :sunglasses:

**Comment by rmrhz** [comment]
Why not just use the RC release to test things out? Either way, most of the functionality would simply be the same. Given that you'll be also providing feedback whenever you'd encounter something

**Comment by cryode** [comment]
I certainly could use the RC release, and I will during my project's development. However, if an experienced developer like myself can run into conflicts, so can someone less experienced. And they will likely have little to no idea what to do about it. Providing even a small bit of documentation for how to circumvent the issue would be better than nothing. :)

**Comment by rmrhz** [comment]
I highly doubt inexperienced developers would run into problems. As you say, they're inexperienced. No intentional offense implied. Though if you can observe people who are using individual components such as these, safe to assume they know what they're doing.

**Comment by cryode** [comment]
In the world of open source libraries, that's a poor assumption to make. You always want to help your users, without assuming their skill levels. Sometimes people will require these libraries as they begin to play around, attempting to learn, maybe following a tutorial or two.




A simple blurb in a readme is a much better solution than convincing yourself that everyone is smart enough to not make a mistake.

**Comment by rmrhz** [comment]
Wrong context though, but still a good point.

Point is, whether experience can be assumed what I define *inexperienced* are on the borderline of venturing out of their comfort zone or simply saying just playing it safe. There's a different culture here on the other side of the world, and generalizing the idea is also a poor assumption.

**Comment by cryode** [comment]
I'm not sure I follow on what the "correct context" would be.

> There's a different culture here on the other side of the world

That's an elitist attitude and *exactly* what people should consciously avoid.

**Comment by philipobenito** [comment]
I think this discussion has gone a little off topic. @cryode it is a general version mismatch error that I agree is confusing, however, for how close we are to release of the new version, I don't see too much benefit to documenting as the same people who would take the time to find that documentation I think would know where to look for the issue and see the version mismatch in a timely manor.
