### ISSUE TITLE
Misleading Exception Message v2

### ISSUE THREAD

**Issue by jamesdb** [thephpleague/route#84]
When registering a controller action and supplying an invalid method an exception is thrown as follows:

```
Catchable fatal error: Argument 1 passed to League\Route\Strategy\JsonStrategy::dispatch() must be callable, array given, called in <snip>/src/Route.php on line 79 and defined in <snip>vendor/league/route/src/Strategy/JsonStrategy.php on line 16
```

This occurs regardless of Strategy used.

A more descriptive exception needs to be thrown which more accurately describes that the method is invalid.

**Comment by philipobenito** [comment]
Yup, just needs to be caught earlier as it's attempting to build an array based callable regardless of whether the method exists.

I'll get on it.

**Comment by jamesdb** [comment]
:+1:

**Comment by jamesdb** [comment]
Not sure if you've had a chance to look at this yet but i've had a go at this, feel free to take it or leave it.
