### ISSUE TITLE
Documentation v2

### ISSUE THREAD

**Issue by Eragon666** [thephpleague/route#87]
Hello!

I just started to use this library after a long search for the perfect router class/framework/library for my project(s). And with the additions in V2 I think this is the perfect class for my needs!

But I only miss the documentation for the second version, I am now developing with help of the code and the unit tests. But I am sure that I miss some nice features this way :)

Has someone already started with early version of the documentation? 

Also I would like to help with the documentation if needed, just let me know and I will see if I can help!

Kind regards,

Matthijs

**Comment by philipobenito** [comment]
I've taken my eye off the ball recently and not had time to finish this but it is coming very, I will aim to get a draft of the docs for v2 pushed by the end of the week.

**Comment by cringer** [comment]
Jan 15th... any update?

**Comment by philipobenito** [comment]
Pushed :+1:
