### ISSUE TITLE
Best way for authentication

### ISSUE THREAD

**Issue by Eragon666** [thephpleague/route#94]
Hi, 

What would be the best way to implement authentication to specified pages? 

Currently I handle the authentication in the Controllers, but it would be nice if I could give a authentication 'flag' to a route (I think this is possible with middleware in Symfony routing?). 

Is there already a build in way to do this? And if not, is this possible to do this with custom strategies? Or is there a better way to accomplish this?

Thanks in advance!

**Comment by hannesvdvreken** [comment]
Are you talking about route v1 or v2? In the case of v1: use stackphp middlewares and check for the request uri to see if authentication needs to be checked.

In the case of v2, use psr-7 middlewares: https://github.com/oscarotero/psr7-middlewares/tree/master/src/Middleware

**Comment by Eragon666** [comment]
@hannesvdvreken thanks for the quick response! 

I am currently using v1 and am waiting for the documentation for v2 before I will make the switch. Mainly because I couldn't figure out how to easily make the transition. 

At this moment I am using namespaced controllers with Symfony Requests and Responses. 
For example for the this route:

```php
$router->addRoute('GET', '/admin/', 'Controller\Dashboard::dashboardGet');
```

I have this controller:
```php
class Dashboard extends BaseController
{    
    
    /*
     * @route admin/dashboard
     */
    public function dashboardGet(Request $request, Response $response) {                
        
        parent::saveRequest($request, $response);
        
        return $this->twigResponse('dashboard/base.html', []);
    }
}
```

But when I switch over to v2 I get an error saying something about that I don't have the Container request or response (something like that, I can't remember exactly). 

Do you know if it's still possible to work with Symfony Request or Response, or do I have to use something else?

**Comment by hannesvdvreken** [comment]
Hi,

You can of course go from Symfony Request and Response objects to PSR-7 objects and back using this bridge package: https://packagist.org/packages/symfony/psr-http-message-bridge

Use where needed for libraries, like oauth2-server from the php league, but generally try to use Psr\Http\Message\RequestInterface as a type hint for Request objects (and ResponseInterface for Response objects).

I hope this answers your questions.

**Comment by Eragon666** [comment]
Hello,

Thanks for your help. I have succesfully updated to version2 now :) 

I am now looking into the psr-7 middleware. So I will try the develop branch for the LeagueRouter middleware :)

Thanks a lot for your help! 

I did open another issue/feature request for nested route groups.

**Comment by hannesvdvreken** [comment]
Quick last tip: use tagged version `2.0.0-RC1` instead of `dev-develop`.
