### ISSUE TITLE
Use PSR-7

### ISSUE THREAD

**Issue by kingkorf** [thephpleague/route#95]
http://www.php-fig.org/psr/psr-7/

**Comment by hannesvdvreken** [comment]
Hi,

Version 2.0.0 will use PSR-7. There is a Release Candidate out if you like to test it out: https://github.com/thephpleague/route/tree/2.0.0-RC1

**Comment by kingkorf** [comment]
That's nice, didn't see that one :+1:

**Comment by hannesvdvreken** [comment]
No problem. Close this issue if you're good.
