### ISSUE TITLE
Enable file caching of route data via var_export

### ISSUE THREAD

**Issue by redstrike** [thephpleague/route#97]
I was not a fan of Front Controller pattern in PHP, but I am trying to force myself to follow the movement of open source frameworks. So I think FastRoute\cachedDispatcher could reduce the overhead of dispatching process as much as possible (of course, I know this is a premature optimization). I wonder, does league's route support it? I cannot found any declaration of that class in the source code.

**Comment by philipobenito** [comment]
Hi, the cached dispatcher is not currently implemented but it is in mind for the next feature release 2.1.0

**Comment by redstrike** [comment]
(y) Hope version 2.1.0 could be released soon.

**Comment by philipobenito** [comment]
Having had a look at the simplicity of this it may be something that we can introduce in to the upcoming 2.0.0 release. I will take a look at the best way to implement it when dispatching and attach results to this issue.

**Comment by wtracz** [comment]
Hi @philipobenito,

I'm happy to help with introducing this caching mechanism. Do you have some thoughts already on the approach? 

Currently my proposition would be to introduce an indirection in the getDispatcher() method.

Thanks,

**Comment by philipobenito** [comment]
@wtracz It is actually a little more complex than originally though, we cannot just enable caching via FastRoute as league/container adds extra functionality. It will have to be a completely new caching system that I'm aiming to look at after the 2.0.0 release.

**Comment by philipobenito** [comment]
This is now out of the scope of what can be done so closing for now. However, I will come back to the idea of caching or compiling a route collection at some point.
